In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mysql.connector

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Nishant@123",
    database="car_price_prediction"
)

print("MySQL connection successful!")

MySQL connection successful!

In [3]:
query = """
SELECT *
FROM cars;
"""

df = pd.read_sql(query, connection)

df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_22968\2741079312.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

,id,car_name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,1,Maruti 800 AC,2007,60000.0,70000,Petrol,Individual,Manual,First Owner
1,2,Maruti Wagon R LXI Minor,2007,135000.0,50000,Petrol,Individual,Manual,First Owner
2,3,Hyundai Verna 1.6 SX,2012,600000.0,100000,Diesel,Individual,Manual,First Owner
3,4,Datsun RediGO T Option,2017,250000.0,46000,Petrol,Individual,Manual,First Owner
4,5,Honda Amaze VX i-DTEC,2014,450000.0,141000,Diesel,Individual,Manual,Second Owner

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 3577
Columns: 9

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3577 entries, 0 to 3576
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             3577 non-null   int64
 1   car_name       3577 non-null   str
 2   year           3577 non-null   int64
 3   selling_price  3577 non-null   float64
 4   km_driven      3577 non-null   int64
 5   fuel           3577 non-null   str
 6   seller_type    3577 non-null   str
 7   transmission   3577 non-null   str
 8   owner          3577 non-null   str
dtypes: float64(1), int64(3), str(5)
memory usage: 452.3 KB

In [6]:
df.isnull().sum()

id               0
car_name         0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [7]:
df.describe()

                id         year  selling_price      km_driven
count  3577.000000  3577.000000   3.577000e+03    3577.000000
mean   2087.193458  2012.962538   4.739125e+05   69250.545709
std    1254.720507     4.251759   5.093018e+05   47579.940016
min       1.000000  1992.000000   2.000000e+04       1.000000
25%    1026.000000  2010.000000   2.000000e+05   36000.000000
50%    2012.000000  2013.000000   3.500000e+05   60000.000000
75%    3193.000000  2016.000000   6.000000e+05   90000.000000
max    4340.000000  2020.000000   8.900000e+06  806599.000000

In [8]:
X=df.drop("selling_price",axis=1)
y=df["selling_price"]

In [9]:
print("Input features:")
print(X.columns)

print("\nTarget:")
print(y.name)

Input features:
Index(['id', 'car_name', 'year', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='str')

Target:
selling_price

In [10]:
X = X.drop("id", axis=1)

In [11]:
numeric_features = [
    "year",
    "car_age",
    "km_driven"
]

categorical_features = [
    "fuel",
    "seller_type",
    "transmission",
    "owner"
]

In [12]:
X = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True
)

In [13]:
X.head()

,car_name,year,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti 800 AC,2007,70000,False,False,False,True,True,False,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,50000,False,False,False,True,True,False,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,100000,True,False,False,False,True,False,True,False,False,False,False
3,Datsun RediGO T Option,2017,46000,False,False,False,True,True,False,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,141000,True,False,False,False,True,False,True,False,True,False,False

In [14]:
print(X.shape)

(3577, 14)

In [15]:
X = X.drop("car_name", axis=1)

In [16]:
X = X.astype(float)

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
print(tf.__version__)

2.22.0-rc0

In [76]:
model = Sequential([
    Dense(599, activation="relu"),
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [77]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=['mse']
)

In [78]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_33 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_36 (Dense)                │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_37 (Dense)                │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [79]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [80]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=1000,
    batch_size=52,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - loss: 452674715648.0000 - mse: 452674715648.0000 - val_loss: 519668367360.0000 - val_mse: 519668367360.0000
Epoch 2/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 451804430336.0000 - mse: 451804430336.0000 - val_loss: 516356734976.0000 - val_mse: 516356734976.0000
Epoch 3/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 437982560256.0000 - mse: 437982560256.0000 - val_loss: 479011405824.0000 - val_mse: 479011405824.0000
Epoch 4/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 354782117888.0000 - mse: 354782117888.0000 - val_loss: 319672352768.0000 - val_mse: 319672352768.0000
Epoch 5/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 188499836928.0000 - mse: 188499836928.0000 - val_loss: 179648446464.0000 - val_mse: 179648446464.0000
Epoch 6/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137755410432.0000 - mse: 137755410432.0000 - val_loss: 166240731136.0000 - val_mse: 166240731136.0000
Epoch 7/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 129330896896.0000 - mse: 129330896896.0000 - val_loss: 158495522816.0000 - val_mse: 158495522816.0000
Epoch 8/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 124649226240.0000 - mse: 124649226240.0000 - val_loss: 153812713472.0000 - val_mse: 153812713472.0000
Epoch 9/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 121995051008.0000 - mse: 121995051008.0000 - val_loss: 150907174912.0000 - val_mse: 150907174912.0000
Epoch 10/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 120442617856.0000 - mse: 120442617856.0000 - val_loss: 149024292864.0000 - val_mse: 149024292864.0000
Epoch 11/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 119477190656.0000 - mse: 119477190656.0000 - val_loss: 147721846784.0000 - val_mse: 147721846784.0000
Epoch 12/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 118821380096.0000 - mse: 118821380096.0000 - val_loss: 146759598080.0000 - val_mse: 146759598080.0000
Epoch 13/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 118326034432.0000 - mse: 118326034432.0000 - val_loss: 145996775424.0000 - val_mse: 145996775424.0000
Epoch 14/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117915394048.0000 - mse: 117915394048.0000 - val_loss: 145348100096.0000 - val_mse: 145348100096.0000
Epoch 15/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117547982848.0000 - mse: 117547982848.0000 - val_loss: 144758439936.0000 - val_mse: 144758439936.0000
Epoch 16/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 117204467712.0000 - mse: 117204467712.0000 - val_loss: 144208674816.0000 - val_mse: 144208674816.0000
Epoch 17/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 116873732096.0000 - mse: 116873732096.0000 - val_loss: 143687401472.0000 - val_mse: 143687401472.0000
Epoch 18/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 116550754304.0000 - mse: 116550754304.0000 - val_loss: 143184756736.0000 - val_mse: 143184756736.0000
Epoch 19/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 116235493376.0000 - mse: 116235493376.0000 - val_loss: 142700642304.0000 - val_mse: 142700642304.0000
Epoch 20/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 115923623936.0000 - mse: 115923632128.0000 - val_loss: 142228094976.0000 - val_mse: 142228094976.0000
Epoch 21/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 115614392320.0000 - mse: 115614392320.0000 - val_loss: 141764788224.0000 - val_mse: 141764788224.0000
Epoch 22/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 115310198784.0000 - mse: 115310198784.0000 - val_loss: 141316456448.0000 - val_mse: 141316456448.0000
Epoch 23/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 115011117056.0000 - mse: 115011117056.0000 - val_loss: 140875268096.0000 - val_mse: 140875268096.0000
Epoch 24/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 114718474240.0000 - mse: 114718474240.0000 - val_loss: 140449775616.0000 - val_mse: 140449792000.0000
Epoch 25/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 114433490944.0000 - mse: 114433490944.0000 - val_loss: 140037111808.0000 - val_mse: 140037111808.0000
Epoch 26/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 114159222784.0000 - mse: 114159222784.0000 - val_loss: 139641978880.0000 - val_mse: 139641978880.0000
Epoch 27/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 113897095168.0000 - mse: 113897095168.0000 - val_loss: 139253153792.0000 - val_mse: 139253153792.0000
Epoch 28/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 113645232128.0000 - mse: 113645240320.0000 - val_loss: 138878812160.0000 - val_mse: 138878812160.0000
Epoch 29/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 113402560512.0000 - mse: 113402560512.0000 - val_loss: 138516201472.0000 - val_mse: 138516201472.0000
Epoch 30/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 113172422656.0000 - mse: 113172422656.0000 - val_loss: 138167435264.0000 - val_mse: 138167435264.0000
Epoch 31/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 112952197120.0000 - mse: 112952197120.0000 - val_loss: 137827188736.0000 - val_mse: 137827188736.0000
Epoch 32/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 112737976320.0000 - mse: 112737976320.0000 - val_loss: 137499328512.0000 - val_mse: 137499328512.0000
Epoch 33/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 112530849792.0000 - mse: 112530849792.0000 - val_loss: 137177120768.0000 - val_mse: 137177120768.0000
Epoch 34/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 112331186176.0000 - mse: 112331177984.0000 - val_loss: 136863129600.0000 - val_mse: 136863129600.0000
Epoch 35/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 112141508608.0000 - mse: 112141508608.0000 - val_loss: 136556863488.0000 - val_mse: 136556863488.0000
Epoch 36/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111959597056.0000 - mse: 111959597056.0000 - val_loss: 136259788800.0000 - val_mse: 136259788800.0000
Epoch 37/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111785230336.0000 - mse: 111785230336.0000 - val_loss: 135969603584.0000 - val_mse: 135969603584.0000
Epoch 38/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111616876544.0000 - mse: 111616876544.0000 - val_loss: 135688470528.0000 - val_mse: 135688470528.0000
Epoch 39/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111457509376.0000 - mse: 111457509376.0000 - val_loss: 135411982336.0000 - val_mse: 135411982336.0000
Epoch 40/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 111301410816.0000 - mse: 111301410816.0000 - val_loss: 135142670336.0000 - val_mse: 135142670336.0000
Epoch 41/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 111149506560.0000 - mse: 111149498368.0000 - val_loss: 134880190464.0000 - val_mse: 134880190464.0000
Epoch 42/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 111000846336.0000 - mse: 111000846336.0000 - val_loss: 134626312192.0000 - val_mse: 134626312192.0000
Epoch 43/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 110859255808.0000 - mse: 110859255808.0000 - val_loss: 134377635840.0000 - val_mse: 134377635840.0000
Epoch 44/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110719246336.0000 - mse: 110719246336.0000 - val_loss: 134138421248.0000 - val_mse: 134138421248.0000
Epoch 45/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110584119296.0000 - mse: 110584119296.0000 - val_loss: 133903499264.0000 - val_mse: 133903499264.0000
Epoch 46/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110453145600.0000 - mse: 110453137408.0000 - val_loss: 133679611904.0000 - val_mse: 133679611904.0000
Epoch 47/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 110327005184.0000 - mse: 110327005184.0000 - val_loss: 133462769664.0000 - val_mse: 133462769664.0000
Epoch 48/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110205067264.0000 - mse: 110205067264.0000 - val_loss: 133258149888.0000 - val_mse: 133258149888.0000
Epoch 49/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110085791744.0000 - mse: 110085791744.0000 - val_loss: 133056937984.0000 - val_mse: 133056954368.0000
Epoch 50/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109971324928.0000 - mse: 109971324928.0000 - val_loss: 132867964928.0000 - val_mse: 132867964928.0000
Epoch 51/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109859954688.0000 - mse: 109859954688.0000 - val_loss: 132681474048.0000 - val_mse: 132681474048.0000
Epoch 52/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109754925056.0000 - mse: 109754925056.0000 - val_loss: 132505878528.0000 - val_mse: 132505878528.0000
Epoch 53/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109652434944.0000 - mse: 109652434944.0000 - val_loss: 132331298816.0000 - val_mse: 132331298816.0000
Epoch 54/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109554778112.0000 - mse: 109554769920.0000 - val_loss: 132167098368.0000 - val_mse: 132167098368.0000
Epoch 55/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 109459251200.0000 - mse: 109459251200.0000 - val_loss: 132006092800.0000 - val_mse: 132006092800.0000
Epoch 56/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109368344576.0000 - mse: 109368344576.0000 - val_loss: 131854540800.0000 - val_mse: 131854540800.0000
Epoch 57/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109280231424.0000 - mse: 109280231424.0000 - val_loss: 131709329408.0000 - val_mse: 131709329408.0000
Epoch 58/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109191053312.0000 - mse: 109191069696.0000 - val_loss: 131565756416.0000 - val_mse: 131565756416.0000
Epoch 59/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109107625984.0000 - mse: 109107625984.0000 - val_loss: 131424321536.0000 - val_mse: 131424321536.0000
Epoch 60/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109025591296.0000 - mse: 109025591296.0000 - val_loss: 131292151808.0000 - val_mse: 131292151808.0000
Epoch 61/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108945965056.0000 - mse: 108945965056.0000 - val_loss: 131163480064.0000 - val_mse: 131163496448.0000
Epoch 62/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 108869926912.0000 - mse: 108869926912.0000 - val_loss: 131040952320.0000 - val_mse: 131040952320.0000
Epoch 63/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108796182528.0000 - mse: 108796182528.0000 - val_loss: 130923462656.0000 - val_mse: 130923462656.0000
Epoch 64/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108723118080.0000 - mse: 108723118080.0000 - val_loss: 130809905152.0000 - val_mse: 130809905152.0000
Epoch 65/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108653527040.0000 - mse: 108653527040.0000 - val_loss: 130701492224.0000 - val_mse: 130701492224.0000
Epoch 66/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108585484288.0000 - mse: 108585484288.0000 - val_loss: 130597044224.0000 - val_mse: 130597044224.0000
Epoch 67/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108518662144.0000 - mse: 108518662144.0000 - val_loss: 130494750720.0000 - val_mse: 130494750720.0000
Epoch 68/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108452487168.0000 - mse: 108452487168.0000 - val_loss: 130398232576.0000 - val_mse: 130398232576.0000
Epoch 69/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108388597760.0000 - mse: 108388597760.0000 - val_loss: 130306015232.0000 - val_mse: 130306015232.0000
Epoch 70/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108326338560.0000 - mse: 108326338560.0000 - val_loss: 130219040768.0000 - val_mse: 130219040768.0000
Epoch 71/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108265725952.0000 - mse: 108265725952.0000 - val_loss: 130133778432.0000 - val_mse: 130133778432.0000
Epoch 72/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108205817856.0000 - mse: 108205809664.0000 - val_loss: 130050801664.0000 - val_mse: 130050801664.0000
Epoch 73/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 108145680384.0000 - mse: 108145680384.0000 - val_loss: 129971470336.0000 - val_mse: 129971470336.0000
Epoch 74/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108086927360.0000 - mse: 108086927360.0000 - val_loss: 129893466112.0000 - val_mse: 129893466112.0000
Epoch 75/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108028411904.0000 - mse: 108028420096.0000 - val_loss: 129821835264.0000 - val_mse: 129821835264.0000
Epoch 76/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107971158016.0000 - mse: 107971158016.0000 - val_loss: 129752121344.0000 - val_mse: 129752121344.0000
Epoch 77/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107916124160.0000 - mse: 107916124160.0000 - val_loss: 129689083904.0000 - val_mse: 129689083904.0000
Epoch 78/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107862179840.0000 - mse: 107862179840.0000 - val_loss: 129623097344.0000 - val_mse: 129623097344.0000
Epoch 79/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107809488896.0000 - mse: 107809488896.0000 - val_loss: 129561681920.0000 - val_mse: 129561681920.0000
Epoch 80/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107758411776.0000 - mse: 107758428160.0000 - val_loss: 129502609408.0000 - val_mse: 129502609408.0000
Epoch 81/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107708538880.0000 - mse: 107708538880.0000 - val_loss: 129445814272.0000 - val_mse: 129445814272.0000
Epoch 82/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107658436608.0000 - mse: 107658436608.0000 - val_loss: 129390780416.0000 - val_mse: 129390780416.0000
Epoch 83/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107610456064.0000 - mse: 107610456064.0000 - val_loss: 129338589184.0000 - val_mse: 129338589184.0000
Epoch 84/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107563745280.0000 - mse: 107563737088.0000 - val_loss: 129289805824.0000 - val_mse: 129289805824.0000
Epoch 85/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107518115840.0000 - mse: 107518124032.0000 - val_loss: 129241628672.0000 - val_mse: 129241628672.0000
Epoch 86/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107473027072.0000 - mse: 107473027072.0000 - val_loss: 129194606592.0000 - val_mse: 129194606592.0000
Epoch 87/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107427094528.0000 - mse: 107427094528.0000 - val_loss: 129149149184.0000 - val_mse: 129149149184.0000
Epoch 88/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107383267328.0000 - mse: 107383275520.0000 - val_loss: 129107574784.0000 - val_mse: 129107574784.0000
Epoch 89/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107341012992.0000 - mse: 107341012992.0000 - val_loss: 129067974656.0000 - val_mse: 129067974656.0000
Epoch 90/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107298660352.0000 - mse: 107298660352.0000 - val_loss: 129031241728.0000 - val_mse: 129031241728.0000
Epoch 91/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107257364480.0000 - mse: 107257364480.0000 - val_loss: 128995475456.0000 - val_mse: 128995475456.0000
Epoch 92/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107220180992.0000 - mse: 107220180992.0000 - val_loss: 128962887680.0000 - val_mse: 128962887680.0000
Epoch 93/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107177066496.0000 - mse: 107177066496.0000 - val_loss: 128925777920.0000 - val_mse: 128925777920.0000
Epoch 94/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107136450560.0000 - mse: 107136450560.0000 - val_loss: 128897302528.0000 - val_mse: 128897302528.0000
Epoch 95/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107097399296.0000 - mse: 107097399296.0000 - val_loss: 128864919552.0000 - val_mse: 128864919552.0000
Epoch 96/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107059109888.0000 - mse: 107059109888.0000 - val_loss: 128837246976.0000 - val_mse: 128837246976.0000
Epoch 97/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107021033472.0000 - mse: 107021033472.0000 - val_loss: 128807182336.0000 - val_mse: 128807182336.0000
Epoch 98/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106981916672.0000 - mse: 106981916672.0000 - val_loss: 128781148160.0000 - val_mse: 128781148160.0000
Epoch 99/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106944233472.0000 - mse: 106944233472.0000 - val_loss: 128755965952.0000 - val_mse: 128755965952.0000
Epoch 100/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106906345472.0000 - mse: 106906345472.0000 - val_loss: 128733085696.0000 - val_mse: 128733085696.0000
Epoch 101/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106869383168.0000 - mse: 106869383168.0000 - val_loss: 128711581696.0000 - val_mse: 128711581696.0000
Epoch 102/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106830815232.0000 - mse: 106830815232.0000 - val_loss: 128691027968.0000 - val_mse: 128691027968.0000
Epoch 103/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106795081728.0000 - mse: 106795089920.0000 - val_loss: 128669327360.0000 - val_mse: 128669327360.0000
Epoch 104/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106759118848.0000 - mse: 106759118848.0000 - val_loss: 128648953856.0000 - val_mse: 128648953856.0000
Epoch 105/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106722566144.0000 - mse: 106722566144.0000 - val_loss: 128629407744.0000 - val_mse: 128629407744.0000
Epoch 106/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106686054400.0000 - mse: 106686054400.0000 - val_loss: 128608616448.0000 - val_mse: 128608616448.0000
Epoch 107/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106648584192.0000 - mse: 106648576000.0000 - val_loss: 128591036416.0000 - val_mse: 128591036416.0000
Epoch 108/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106613424128.0000 - mse: 106613424128.0000 - val_loss: 128577404928.0000 - val_mse: 128577404928.0000
Epoch 109/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106579976192.0000 - mse: 106579976192.0000 - val_loss: 128563691520.0000 - val_mse: 128563691520.0000
Epoch 110/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106546880512.0000 - mse: 106546880512.0000 - val_loss: 128551510016.0000 - val_mse: 128551510016.0000
Epoch 111/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106515947520.0000 - mse: 106515947520.0000 - val_loss: 128536330240.0000 - val_mse: 128536330240.0000
Epoch 112/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106481721344.0000 - mse: 106481721344.0000 - val_loss: 128524599296.0000 - val_mse: 128524599296.0000
Epoch 113/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106450534400.0000 - mse: 106450534400.0000 - val_loss: 128508436480.0000 - val_mse: 128508436480.0000
Epoch 114/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106415587328.0000 - mse: 106415587328.0000 - val_loss: 128500416512.0000 - val_mse: 128500416512.0000
Epoch 115/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 106385096704.0000 - mse: 106385096704.0000 - val_loss: 128487956480.0000 - val_mse: 128487956480.0000
Epoch 116/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106355990528.0000 - mse: 106355990528.0000 - val_loss: 128475660288.0000 - val_mse: 128475660288.0000
Epoch 117/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106324156416.0000 - mse: 106324156416.0000 - val_loss: 128466026496.0000 - val_mse: 128466026496.0000
Epoch 118/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106294788096.0000 - mse: 106294771712.0000 - val_loss: 128453394432.0000 - val_mse: 128453394432.0000
Epoch 119/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106264666112.0000 - mse: 106264657920.0000 - val_loss: 128445636608.0000 - val_mse: 128445636608.0000
Epoch 120/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106236968960.0000 - mse: 106236968960.0000 - val_loss: 128435822592.0000 - val_mse: 128435822592.0000
Epoch 121/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106207494144.0000 - mse: 106207502336.0000 - val_loss: 128429957120.0000 - val_mse: 128429957120.0000
Epoch 122/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106180935680.0000 - mse: 106180935680.0000 - val_loss: 128419561472.0000 - val_mse: 128419577856.0000
Epoch 123/1000

In [81]:
y_pred = model.predict(X_test)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step

In [82]:
y_pred = y_pred.flatten()

In [83]:
print(y_pred[:10])

[5.0457312e+05 5.2203403e+05 6.7420500e+05 2.2339835e+06 1.5098125e+05
 2.6150536e+05 1.3959131e+05 7.1168719e+05 9.7887806e+05 3.1948866e+05]

In [28]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 185071.20603286487

In [29]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 169845556630.98303

In [84]:
from sklearn.metrics import r2_score

r2=r2_score(y_test , y_pred)
r2

0.49259162511741106

In [31]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 412123.2299094326

In [32]:
print("Model Evaluation")
print("---------------------------")
print("MAE  :", mae)
print("MSE  :", mse)
print("RMSE :", rmse)
print("R²   :", r2)

Model Evaluation
---------------------------
MAE  : 185071.20603286487
MSE  : 169845556630.98303
RMSE : 412123.2299094326
R²   : 0.4727476858286782

In [33]:
results = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

results.head(20)

    Actual Price  Predicted Price
0       270000.0     4.974250e+05
1       525000.0     4.669639e+05
2       990000.0     6.799097e+05
3      3800000.0     1.949911e+06
4       229999.0     1.410690e+05
5       325000.0     2.855185e+05
6       210000.0     1.426002e+05
7       500000.0     7.163642e+05
8       790000.0     9.647753e+05
9       360000.0     2.851278e+05
10      250000.0     3.754998e+05
11      160000.0     2.223227e+05
12      500000.0     8.450356e+05
13      229999.0     2.569793e+05
14      360000.0     4.073786e+05
15      612000.0     3.076233e+05
16      350000.0     3.619828e+05
17      800000.0     9.463492e+05
18      160000.0     3.364151e+05
19      330000.0     2.791228e+05

In [34]:
results["Error"] = (
    results["Actual Price"] - results["Predicted Price"]
)

results.head(20)

    Actual Price  Predicted Price         Error
0       270000.0     4.974250e+05 -2.274250e+05
1       525000.0     4.669639e+05  5.803609e+04
2       990000.0     6.799097e+05  3.100903e+05
3      3800000.0     1.949911e+06  1.850089e+06
4       229999.0     1.410690e+05  8.892995e+04
5       325000.0     2.855185e+05  3.948150e+04
6       210000.0     1.426002e+05  6.739981e+04
7       500000.0     7.163642e+05 -2.163642e+05
8       790000.0     9.647753e+05 -1.747753e+05
9       360000.0     2.851278e+05  7.487216e+04
10      250000.0     3.754998e+05 -1.254998e+05
11      160000.0     2.223227e+05 -6.232266e+04
12      500000.0     8.450356e+05 -3.450356e+05
13      229999.0     2.569793e+05 -2.698031e+04
14      360000.0     4.073786e+05 -4.737862e+04
15      612000.0     3.076233e+05  3.043767e+05
16      350000.0     3.619828e+05 -1.198278e+04
17      800000.0     9.463492e+05 -1.463492e+05
18      160000.0     3.364151e+05 -1.764151e+05
19      330000.0     2.791228e+05  5.087719e+04

In [35]:
query = """
SELECT
    id,
    car_name,
    year,
    km_driven,
    fuel,
    seller_type,
    transmission,
    owner,
    selling_price
FROM cars;
"""

df_v2 = pd.read_sql(query, connection)

print(df_v2.shape)
df_v2.head()

(3577, 9)

C:\Users\HP\AppData\Local\Temp\ipykernel_22968\1089843448.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v2 = pd.read_sql(query, connection)

,id,car_name,year,km_driven,fuel,seller_type,transmission,owner,selling_price
0,1,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,60000.0
1,2,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,135000.0
2,3,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,600000.0
3,4,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,250000.0
4,5,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,450000.0

In [36]:
df_v2["car_brand"] = (
    df_v2["car_name"]
    .str.strip()
    .str.split()
    .str[0]
    .str.title()
)

print(df_v2[["car_name", "car_brand"]].head(15))

                           car_name  car_brand
0                     Maruti 800 AC     Maruti
1          Maruti Wagon R LXI Minor     Maruti
2              Hyundai Verna 1.6 SX    Hyundai
3            Datsun RediGO T Option     Datsun
4             Honda Amaze VX i-DTEC      Honda
5              Maruti Alto LX BSIII     Maruti
6         Hyundai Xcent 1.2 Kappa S    Hyundai
7          Tata Indigo Grand Petrol       Tata
8          Hyundai Creta 1.6 VTVT S    Hyundai
9          Maruti Celerio Green VXI     Maruti
10          Chevrolet Sail 1.2 Base  Chevrolet
11         Tata Indigo Grand Petrol       Tata
12  Toyota Corolla Altis 1.8 VL CVT     Toyota
13             Maruti Ciaz VXi Plus     Maruti
14      Hyundai Venue SX Opt Diesel    Hyundai

In [37]:
df_v2["car_age"]=2026-df["year"]

In [38]:
df_v2["car_age"]=2026-df["year"]
df_v2.head()

,id,car_name,year,km_driven,fuel,seller_type,transmission,owner,selling_price,car_brand,car_age
0,1,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,60000.0,Maruti,19
1,2,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,135000.0,Maruti,19
2,3,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,600000.0,Hyundai,14
3,4,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,250000.0,Datsun,9
4,5,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,450000.0,Honda,12

In [39]:
numeric_features=[ "year",
                       "km_driven" ,
                       "car_age"
]

categorical_features=["car_name",
                           "fuel",
                           "seller_type",
                           "transmission",
                           "owner",
                           "car_brand"]

X_v2 = df_v2[numeric_features + categorical_features].copy()
y_v2 = df_v2["selling_price"].copy()

X_v2=pd.get_dummies(
    X_v2,
    columns=categorical_features,
    drop_first=True,
    dtype=int
)

print( X_v2.shape[1])
X_v2.head()

1532

,year,km_driven,car_age,car_name_Ambassador Classic 2000 Dsz,car_name_Ambassador Grand 1800 ISZ MPFI PW CL,car_name_Audi A4 1.8 TFSI,car_name_Audi A4 2.0 TDI,car_name_Audi A4 2.0 TDI 177 Bhp Premium Plus,car_name_Audi A4 3.0 TDI Quattro,car_name_Audi A4 30 TFSI Technology,...,car_brand_Mg,car_brand_Mitsubishi,car_brand_Nissan,car_brand_Opelcorsa,car_brand_Renault,car_brand_Skoda,car_brand_Tata,car_brand_Toyota,car_brand_Volkswagen,car_brand_Volvo
0,2007,70000,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,50000,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2012,100000,14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017,46000,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2014,141000,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train_v2,X_test_v2,y_train_v2,y_test_v2=train_test_split(
    X_v2,
    y_v2,
    test_size=0.20,
    random_state=42
)

scaler_v2 = StandardScaler()
X_train_v2=scaler_v2.fit_transform(X_train_v2)
X_test_v2 = scaler_v2.transform(X_test_v2)

In [41]:
model_v2=Sequential([
    Dense(128 , activation="relu",input_shape=(X_train_v2.shape[1],)),
    Dense(64 , activation="relu"),
    Dense(32 , activation="relu"),
    Dense(1)
])

model_v2.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

history_v2 = model_v2.fit(
    X_train_v2,
    y_train_v2,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1

)

Epoch 1/100

C:\Users\HP\AppData\Roaming\Python\Python314\site-packages\keras\src\layers\core\dense.py:102: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 452640800768.0000 - mae: 471139.5938 - val_loss: 519519993856.0000 - val_mae: 473748.2188
Epoch 2/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 450423816192.0000 - mae: 468988.6562 - val_loss: 514733768704.0000 - val_mae: 468994.0000
Epoch 3/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 430574796800.0000 - mae: 449685.4688 - val_loss: 486953746432.0000 - val_mae: 440046.7188
Epoch 4/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 362006511616.0000 - mae: 376420.1250 - val_loss: 421854806016.0000 - val_mae: 361654.9375
Epoch 5/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 259580248064.0000 - mae: 266728.7812 - val_loss: 370255724544.0000 - val_mae: 320695.1562
Epoch 6/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 202823778304.0000 - mae: 224493.2656 - val_loss: 356426678272.0000 - val_mae: 317795.2812
Epoch 7/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 180421902336.0000 - mae: 206828.8125 - val_loss: 346418806784.0000 - val_mae: 306604.6250
Epoch 8/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 163045801984.0000 - mae: 188397.0469 - val_loss: 337261625344.0000 - val_mae: 294911.1250
Epoch 9/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 147114442752.0000 - mae: 171826.6719 - val_loss: 328773500928.0000 - val_mae: 283977.0000
Epoch 10/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 132204912640.0000 - mae: 156969.9375 - val_loss: 320872251392.0000 - val_mae: 273482.1562
Epoch 11/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 118343589888.0000 - mae: 143091.9531 - val_loss: 313294389248.0000 - val_mae: 265073.1875
Epoch 12/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 105708937216.0000 - mae: 130303.2969 - val_loss: 305726947328.0000 - val_mae: 257857.2500
Epoch 13/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 94478639104.0000 - mae: 118760.9531 - val_loss: 297808953344.0000 - val_mae: 251715.3438
Epoch 14/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 84617904128.0000 - mae: 108774.1562 - val_loss: 289535393792.0000 - val_mae: 246362.6719
Epoch 15/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 75959713792.0000 - mae: 100310.4375 - val_loss: 281235030016.0000 - val_mae: 241981.7344
Epoch 16/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 68395069440.0000 - mae: 93152.9688 - val_loss: 273366548480.0000 - val_mae: 238312.3750
Epoch 17/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 61801992192.0000 - mae: 87060.8359 - val_loss: 266056810496.0000 - val_mae: 234950.8906
Epoch 18/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 56123998208.0000 - mae: 81730.3125 - val_loss: 259365896192.0000 - val_mae: 232001.7969
Epoch 19/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 51244691456.0000 - mae: 77331.7891 - val_loss: 253318856704.0000 - val_mae: 229481.9219
Epoch 20/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 46978990080.0000 - mae: 73387.5391 - val_loss: 247792812032.0000 - val_mae: 227251.2500
Epoch 21/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 43268284416.0000 - mae: 69855.7734 - val_loss: 242756976640.0000 - val_mae: 225002.6719
Epoch 22/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 40039972864.0000 - mae: 66658.9766 - val_loss: 238152450048.0000 - val_mae: 222877.5625
Epoch 23/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 37192093696.0000 - mae: 63968.1680 - val_loss: 233912844288.0000 - val_mae: 220810.8594
Epoch 24/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 34677116928.0000 - mae: 61527.7969 - val_loss: 230039207936.0000 - val_mae: 218794.7500
Epoch 25/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 32453052416.0000 - mae: 59328.5469 - val_loss: 226447245312.0000 - val_mae: 216832.0312
Epoch 26/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30481047552.0000 - mae: 57297.2539 - val_loss: 223164350464.0000 - val_mae: 214944.5000
Epoch 27/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28724967424.0000 - mae: 55442.1875 - val_loss: 220077768704.0000 - val_mae: 213153.2031
Epoch 28/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27148769280.0000 - mae: 53785.7422 - val_loss: 217299877888.0000 - val_mae: 211728.2656
Epoch 29/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25736300544.0000 - mae: 52326.7695 - val_loss: 214631317504.0000 - val_mae: 210267.6094
Epoch 30/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24469331968.0000 - mae: 51079.1641 - val_loss: 212244791296.0000 - val_mae: 208949.3906
Epoch 31/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23324284928.0000 - mae: 50040.4844 - val_loss: 209920032768.0000 - val_mae: 207612.1094
Epoch 32/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 22273839104.0000 - mae: 49007.7109 - val_loss: 207805218816.0000 - val_mae: 206348.2031
Epoch 33/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 21311264768.0000 - mae: 48014.8086 - val_loss: 205659013120.0000 - val_mae: 205161.5781
Epoch 34/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 20423657472.0000 - mae: 47233.4844 - val_loss: 203754422272.0000 - val_mae: 204169.3281
Epoch 35/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 19593742336.0000 - mae: 46557.5156 - val_loss: 201762177024.0000 - val_mae: 202907.6562
Epoch 36/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 18823305216.0000 - mae: 45951.2344 - val_loss: 199889141760.0000 - val_mae: 202019.6250
Epoch 37/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 18107990016.0000 - mae: 45406.7969 - val_loss: 198084771840.0000 - val_mae: 200720.1562
Epoch 38/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 17426556928.0000 - mae: 44916.4180 - val_loss: 196307779584.0000 - val_mae: 199920.9219
Epoch 39/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 16780920832.0000 - mae: 44527.3516 - val_loss: 194612805632.0000 - val_mae: 198609.7969
Epoch 40/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 16165738496.0000 - mae: 44067.2383 - val_loss: 192924549120.0000 - val_mae: 197951.6406
Epoch 41/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 15580760064.0000 - mae: 43636.7109 - val_loss: 191249956864.0000 - val_mae: 196721.2656
Epoch 42/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 15026292736.0000 - mae: 43177.9531 - val_loss: 189626089472.0000 - val_mae: 196069.4375
Epoch 43/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 14502805504.0000 - mae: 42902.7227 - val_loss: 187996569600.0000 - val_mae: 195016.5938
Epoch 44/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 14003132416.0000 - mae: 42595.9727 - val_loss: 186382155776.0000 - val_mae: 194315.5000
Epoch 45/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 13525023744.0000 - mae: 42407.9453 - val_loss: 184759025664.0000 - val_mae: 193343.9531
Epoch 46/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 13068461056.0000 - mae: 42246.9180 - val_loss: 183220420608.0000 - val_mae: 192675.2031
Epoch 47/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 12639435776.0000 - mae: 42193.3594 - val_loss: 181532229632.0000 - val_mae: 191608.9531
Epoch 48/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 12210286592.0000 - mae: 41971.4180 - val_loss: 180026589184.0000 - val_mae: 190951.1250
Epoch 49/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 11800299520.0000 - mae: 41783.2422 - val_loss: 178294767616.0000 - val_mae: 189763.7344
Epoch 50/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 11396514816.0000 - mae: 41536.5703 - val_loss: 176804511744.0000 - val_mae: 189105.1094
Epoch 51/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 11018714112.0000 - mae: 41439.0000 - val_loss: 175101935616.0000 - val_mae: 187992.9375
Epoch 52/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 10647279616.0000 - mae: 41377.4688 - val_loss: 173667598336.0000 - val_mae: 187228.5938
Epoch 53/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 10297967616.0000 - mae: 41377.4062 - val_loss: 171946524672.0000 - val_mae: 186162.4688
Epoch 54/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 9945704448.0000 - mae: 41337.8438 - val_loss: 170538516480.0000 - val_mae: 185324.8594
Epoch 55/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 9613059072.0000 - mae: 41223.7305 - val_loss: 168855945216.0000 - val_mae: 184266.9219
Epoch 56/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 9286581248.0000 - mae: 41105.3867 - val_loss: 167347339264.0000 - val_mae: 183436.2969
Epoch 57/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 8970997760.0000 - mae: 40953.8008 - val_loss: 165685936128.0000 - val_mae: 182421.5312
Epoch 58/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 8677482496.0000 - mae: 40896.7188 - val_loss: 164150624256.0000 - val_mae: 181561.6719
Epoch 59/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 8384074752.0000 - mae: 40759.5703 - val_loss: 162478833664.0000 - val_mae: 180440.9844
Epoch 60/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8112643584.0000 - mae: 40738.9688 - val_loss: 160905265152.0000 - val_mae: 179599.9688
Epoch 61/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7844235776.0000 - mae: 40633.7734 - val_loss: 159298076672.0000 - val_mae: 178501.9688
Epoch 62/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7593794048.0000 - mae: 40590.7773 - val_loss: 157781377024.0000 - val_mae: 177553.1562
Epoch 63/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7348316160.0000 - mae: 40545.9492 - val_loss: 156195258368.0000 - val_mae: 176628.0000
Epoch 64/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7124542976.0000 - mae: 40523.9141 - val_loss: 154714308608.0000 - val_mae: 175376.2031
Epoch 65/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6903284224.0000 - mae: 40437.3789 - val_loss: 153230442496.0000 - val_mae: 174951.1406
Epoch 66/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6700879360.0000 - mae: 40441.8516 - val_loss: 151662034944.0000 - val_mae: 173297.0000
Epoch 67/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6501588480.0000 - mae: 40308.7148 - val_loss: 150209314816.0000 - val_mae: 172846.7188
Epoch 68/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6315300352.0000 - mae: 40187.7344 - val_loss: 148772372480.0000 - val_mae: 171347.5469
Epoch 69/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6141317632.0000 - mae: 40032.9805 - val_loss: 147364462592.0000 - val_mae: 170789.0000
Epoch 70/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5972555264.0000 - mae: 39873.4141 - val_loss: 146076647424.0000 - val_mae: 169683.2188
Epoch 71/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5817530880.0000 - mae: 39669.2461 - val_loss: 144591847424.0000 - val_mae: 168622.6562
Epoch 72/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5677924352.0000 - mae: 39621.8750 - val_loss: 143460073472.0000 - val_mae: 167973.6875
Epoch 73/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5549869056.0000 - mae: 39547.9609 - val_loss: 142008336384.0000 - val_mae: 166719.1406
Epoch 74/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5433455104.0000 - mae: 39532.2383 - val_loss: 140986499072.0000 - val_mae: 166144.8594
Epoch 75/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5318920192.0000 - mae: 39315.0859 - val_loss: 139697192960.0000 - val_mae: 165085.4375
Epoch 76/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5215104512.0000 - mae: 39242.9062 - val_loss: 138679812096.0000 - val_mae: 164268.5000
Epoch 77/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5123122688.0000 - mae: 39096.6562 - val_loss: 137489465344.0000 - val_mae: 163647.1406
Epoch 78/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5038558208.0000 - mae: 39086.2656 - val_loss: 136613339136.0000 - val_mae: 162772.3281
Epoch 79/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4958998016.0000 - mae: 38864.8516 - val_loss: 135547011072.0000 - val_mae: 162255.2188
Epoch 80/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4880827392.0000 - mae: 38716.9727 - val_loss: 134762446848.0000 - val_mae: 161499.7656
Epoch 81/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4814533120.0000 - mae: 38501.6797 - val_loss: 133778857984.0000 - val_mae: 161184.3438
Epoch 82/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4754653184.0000 - mae: 38398.3867 - val_loss: 133031641088.0000 - val_mae: 160448.3594
Epoch 83/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4699727360.0000 - mae: 38224.1445 - val_loss: 132131086336.0000 - val_mae: 160088.7969
Epoch 84/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4655068160.0000 - mae: 38259.9258 - val_loss: 131535085568.0000 - val_mae: 159572.8438
Epoch 85/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4621964288.0000 - mae: 38224.2930 - val_loss: 130739093504.0000 - val_mae: 159174.8125
Epoch 86/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4579063808.0000 - mae: 38147.6523 - val_loss: 130135375872.0000 - val_mae: 158726.2812
Epoch 87/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4540819968.0000 - mae: 37958.2031 - val_loss: 129401454592.0000 - val_mae: 158318.4688
Epoch 88/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4508822528.0000 - mae: 37921.6914 - val_loss: 128989413376.0000 - val_mae: 157899.7344
Epoch 89/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4473821696.0000 - mae: 37670.2812 - val_loss: 128300916736.0000 - val_mae: 157691.1719
Epoch 90/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4449929728.0000 - mae: 37622.3594 - val_loss: 127928303616.0000 - val_mae: 157121.4219
Epoch 91/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4418724352.0000 - mae: 37475.4023 - val_loss: 127328804864.0000 - val_mae: 157075.2188
Epoch 92/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4402013696.0000 - mae: 37411.3164 - val_loss: 127008849920.0000 - val_mae: 156487.5000
Epoch 93/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4374272512.0000 - mae: 37310.9648 - val_loss: 126383005696.0000 - val_mae: 156509.3438
Epoch 94/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4362179072.0000 - mae: 37260.7422 - val_loss: 126300037120.0000 - val_mae: 156060.0312
Epoch 95/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4337310208.0000 - mae: 37092.2617 - val_loss: 125648199680.0000 - val_mae: 156116.0156
Epoch 96/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4326095360.0000 - mae: 37085.4648 - val_loss: 125615570944.0000 - val_mae: 155778.4375
Epoch 97/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 4308273152.0000 - mae: 36972.4258 - val_loss: 125069778944.0000 - val_mae: 155821.0469
Epoch 98/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4298487296.0000 - mae: 36971.1016 - val_loss: 124888760320.0000 - val_mae: 155468.2188
Epoch 99/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4284207872.0000 - mae: 36880.7344 - val_loss: 124711444480.0000 - val_mae: 155634.8125
Epoch 100/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4277476864.0000 - mae: 36859.4492 - val_loss: 124121726976.0000 - val_mae: 155134.4844

In [42]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

y_pred_v2 = model_v2.predict(X_test_v2).flatten()

mae_v2 = mean_absolute_error(y_test_v2, y_pred_v2)
mse_v2 = mean_squared_error(y_test_v2, y_pred_v2)
rmse_v2 = np.sqrt(mse_v2)
r2_v2 = r2_score(y_test_v2, y_pred_v2)

print("ANN Version 2")
print("---------------------------")
print("MAE :", mae_v2)
print("MSE :", mse_v2)
print("RMSE:", rmse_v2)
print("R²  :", r2_v2)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
ANN Version 2
---------------------------
MAE : 395155.5744650217
MSE : 514880336395.8
RMSE: 717551.6262930494
R²  : -0.5983453101208338

In [43]:


print("\nNumber of unique brands:")
print(df_v2["car_brand"].nunique())

Number of unique brands:
29

In [44]:
print("\nMost common brands:")
print(df_v2["car_brand"].value_counts().head(20))

Most common brands:
car_brand
Maruti           1072
Hyundai           637
Mahindra          328
Tata              308
Ford              220
Honda             216
Toyota            170
Chevrolet         151
Renault           110
Volkswagen         93
Nissan             52
Skoda              49
Fiat               32
Audi               31
Datsun             29
Bmw                25
Mercedes-Benz      21
Jaguar              5
Mitsubishi          5
Land                5
Name: count, dtype: int64

In [45]:
print(df_v2["selling_price"].describe())

print("\nMissing values:")
print(df_v2.isnull().sum())

print("\nDuplicate rows:")
print(df_v2.duplicated().sum())

count    3.577000e+03
mean     4.739125e+05
std      5.093018e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

Missing values:
id               0
car_name         0
year             0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
selling_price    0
car_brand        0
car_age          0
dtype: int64

Duplicate rows:
0

In [46]:
print("Training price statistics:")
print(y_train_v2.describe())

print("\nTesting price statistics:")
print(y_test_v2.describe())

Training price statistics:
count    2.861000e+03
mean     4.717467e+05
std      4.936159e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      5.900000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

Testing price statistics:
count    7.160000e+02
mean     4.825667e+05
std      5.679647e+05
min      3.500000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.150000e+06
Name: selling_price, dtype: float64

In [47]:
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Select input features
numeric_features = ["car_age", "km_driven"]
categorical_features = [
    "car_brand", "fuel", "seller_type", "transmission", "owner"
]

X_v3 = df_v2[numeric_features + categorical_features].copy()
y_v3 = df_v2["selling_price"].copy()

# Convert categorical columns into numeric columns
X_v3 = pd.get_dummies(
    X_v3,
    columns=categorical_features,
    drop_first=True,
    dtype=int
)

print("Input shape:", X_v3.shape)
print("Target shape:", y_v3.shape)
print("Missing values:", X_v3.isnull().sum().sum())

Input shape: (3577, 41)
Target shape: (3577,)
Missing values: 0

In [48]:
X_train_v3, X_test_v3, y_train_v3, y_test_v3 = train_test_split(
    X_v3, y_v3, test_size=0.20, random_state=42
)

# Scale input features
scaler_v3 = StandardScaler()

X_train_v3 = scaler_v3.fit_transform(X_train_v3)
X_test_v3 = scaler_v3.transform(X_test_v3)

# Transform target prices using logarithms
y_train_log_v3 = np.log1p(y_train_v3)
y_test_log_v3 = np.log1p(y_test_v3)

print("Training rows:", len(X_train_v3))
print("Testing rows:", len(X_test_v3))
print("Data preparation complete!")

Training rows: 2861
Testing rows: 716
Data preparation complete!

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping

# Set random seed for reproducibility
tf.keras.utils.set_random_seed(42)

# Build ANN model
model_v3 = Sequential([
    Input(shape=(X_train_v3.shape[1],)),
    Dense(1000, activation="relu"),
    Dense(500, activation="relu"),
    Dense(360, activation="relu"),
    Dense(128, activation="relu"),
    Dense(64, activation="relu"),
    Dense(32, activation="relu"),
    Dense(1)
])

# Compile the model
model_v3.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

# Stop training when validation loss stops improving
early_stop_v3 = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

model_v3.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_26 (Dense)                │ (None, 1000)           │        42,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_27 (Dense)                │ (None, 500)            │       500,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 360)            │       180,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 128)            │        46,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_30 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 779,437 (2.97 MB)

 Trainable params: 779,437 (2.97 MB)

 Non-trainable params: 0 (0.00 B)

In [73]:
history_v3 = model_v3.fit(
    X_train_v3,
    y_train_log_v3,
    validation_split=0.2,
    epochs=1000,
    batch_size=100,
    callbacks=[early_stop_v3],
    verbose=1
)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.5132 - mae: 0.5664 - val_loss: 0.2459 - val_mae: 0.3871
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1835 - mae: 0.3236 - val_loss: 0.1788 - val_mae: 0.3233
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1576 - mae: 0.3007 - val_loss: 0.1625 - val_mae: 0.3082
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1443 - mae: 0.2914 - val_loss: 0.1581 - val_mae: 0.3041
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1386 - mae: 0.2869 - val_loss: 0.1555 - val_mae: 0.3013
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1355 - mae: 0.2852 - val_loss: 0.1544 - val_mae: 0.3008
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1330 - mae: 0.2832 - val_loss: 0.1532 - val_mae: 0.2994
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1315 - mae: 0.2820 - val_loss: 0.1533 - val_mae: 0.2999
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1296 - mae: 0.2805 - val_loss: 0.1506 - val_mae: 0.2970
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1287 - mae: 0.2797 - val_loss: 0.1491 - val_mae: 0.2952
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1268 - mae: 0.2775 - val_loss: 0.1481 - val_mae: 0.2943
Epoch 12/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1256 - mae: 0.2763 - val_loss: 0.1472 - val_mae: 0.2935
Epoch 13/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1249 - mae: 0.2755 - val_loss: 0.1462 - val_mae: 0.2925
Epoch 14/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1243 - mae: 0.2749 - val_loss: 0.1454 - val_mae: 0.2919
Epoch 15/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1236 - mae: 0.2741 - val_loss: 0.1446 - val_mae: 0.2911
Epoch 16/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1231 - mae: 0.2734 - val_loss: 0.1436 - val_mae: 0.2902
Epoch 17/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1224 - mae: 0.2726 - val_loss: 0.1428 - val_mae: 0.2894
Epoch 18/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1218 - mae: 0.2718 - val_loss: 0.1418 - val_mae: 0.2885
Epoch 19/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1214 - mae: 0.2712 - val_loss: 0.1411 - val_mae: 0.2877
Epoch 20/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1208 - mae: 0.2706 - val_loss: 0.1403 - val_mae: 0.2870
Epoch 21/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1204 - mae: 0.2700 - val_loss: 0.1400 - val_mae: 0.2867
Epoch 22/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1199 - mae: 0.2693 - val_loss: 0.1395 - val_mae: 0.2863
Epoch 23/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1194 - mae: 0.2687 - val_loss: 0.1388 - val_mae: 0.2853
Epoch 24/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1190 - mae: 0.2682 - val_loss: 0.1384 - val_mae: 0.2851
Epoch 25/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1186 - mae: 0.2676 - val_loss: 0.1376 - val_mae: 0.2841
Epoch 26/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1182 - mae: 0.2670 - val_loss: 0.1374 - val_mae: 0.2837
Epoch 27/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1179 - mae: 0.2667 - val_loss: 0.1370 - val_mae: 0.2833
Epoch 28/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.1175 - mae: 0.2661 - val_loss: 0.1366 - val_mae: 0.2828
Epoch 29/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.1172 - mae: 0.2656 - val_loss: 0.1361 - val_mae: 0.2822
Epoch 30/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1168 - mae: 0.2652 - val_loss: 0.1359 - val_mae: 0.2820
Epoch 31/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1165 - mae: 0.2648 - val_loss: 0.1354 - val_mae: 0.2815
Epoch 32/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1161 - mae: 0.2643 - val_loss: 0.1350 - val_mae: 0.2808
Epoch 33/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1158 - mae: 0.2639 - val_loss: 0.1347 - val_mae: 0.2804
Epoch 34/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1155 - mae: 0.2636 - val_loss: 0.1345 - val_mae: 0.2801
Epoch 35/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1152 - mae: 0.2631 - val_loss: 0.1342 - val_mae: 0.2798
Epoch 36/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1150 - mae: 0.2627 - val_loss: 0.1338 - val_mae: 0.2792
Epoch 37/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1147 - mae: 0.2625 - val_loss: 0.1336 - val_mae: 0.2789
Epoch 38/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1144 - mae: 0.2620 - val_loss: 0.1335 - val_mae: 0.2788
Epoch 39/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1141 - mae: 0.2617 - val_loss: 0.1331 - val_mae: 0.2784
Epoch 40/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1139 - mae: 0.2614 - val_loss: 0.1328 - val_mae: 0.2779
Epoch 41/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1136 - mae: 0.2611 - val_loss: 0.1328 - val_mae: 0.2779
Epoch 42/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.1133 - mae: 0.2608 - val_loss: 0.1326 - val_mae: 0.2777
Epoch 43/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1133 - mae: 0.2606 - val_loss: 0.1323 - val_mae: 0.2770
Epoch 44/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.1127 - mae: 0.2600 - val_loss: 0.1323 - val_mae: 0.2772
Epoch 45/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1127 - mae: 0.2600 - val_loss: 0.1322 - val_mae: 0.2768
Epoch 46/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1123 - mae: 0.2596 - val_loss: 0.1318 - val_mae: 0.2765
Epoch 47/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1121 - mae: 0.2593 - val_loss: 0.1318 - val_mae: 0.2764
Epoch 48/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.1119 - mae: 0.2591 - val_loss: 0.1316 - val_mae: 0.2762
Epoch 49/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1117 - mae: 0.2587 - val_loss: 0.1315 - val_mae: 0.2761
Epoch 50/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1114 - mae: 0.2584 - val_loss: 0.1314 - val_mae: 0.2761
Epoch 51/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1112 - mae: 0.2582 - val_loss: 0.1312 - val_mae: 0.2759
Epoch 52/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1110 - mae: 0.2580 - val_loss: 0.1311 - val_mae: 0.2758
Epoch 53/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1108 - mae: 0.2577 - val_loss: 0.1311 - val_mae: 0.2757
Epoch 54/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1106 - mae: 0.2575 - val_loss: 0.1311 - val_mae: 0.2757
Epoch 55/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1104 - mae: 0.2573 - val_loss: 0.1308 - val_mae: 0.2753
Epoch 56/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1101 - mae: 0.2570 - val_loss: 0.1307 - val_mae: 0.2753
Epoch 57/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1099 - mae: 0.2567 - val_loss: 0.1307 - val_mae: 0.2753
Epoch 58/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1097 - mae: 0.2565 - val_loss: 0.1306 - val_mae: 0.2749
Epoch 59/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1095 - mae: 0.2563 - val_loss: 0.1306 - val_mae: 0.2752
Epoch 60/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1093 - mae: 0.2561 - val_loss: 0.1306 - val_mae: 0.2751
Epoch 61/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1091 - mae: 0.2557 - val_loss: 0.1302 - val_mae: 0.2746
Epoch 62/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1089 - mae: 0.2555 - val_loss: 0.1306 - val_mae: 0.2752
Epoch 63/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1087 - mae: 0.2553 - val_loss: 0.1303 - val_mae: 0.2749
Epoch 64/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.1085 - mae: 0.2550 - val_loss: 0.1302 - val_mae: 0.2748
Epoch 65/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.1083 - mae: 0.2546 - val_loss: 0.1300 - val_mae: 0.2743
Epoch 66/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1081 - mae: 0.2544 - val_loss: 0.1302 - val_mae: 0.2748
Epoch 67/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1079 - mae: 0.2542 - val_loss: 0.1302 - val_mae: 0.2748
Epoch 68/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1077 - mae: 0.2540 - val_loss: 0.1301 - val_mae: 0.2745
Epoch 69/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1076 - mae: 0.2538 - val_loss: 0.1300 - val_mae: 0.2743
Epoch 70/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1073 - mae: 0.2535 - val_loss: 0.1300 - val_mae: 0.2744
Epoch 71/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1071 - mae: 0.2531 - val_loss: 0.1298 - val_mae: 0.2743
Epoch 72/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1069 - mae: 0.2529 - val_loss: 0.1298 - val_mae: 0.2741
Epoch 73/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1067 - mae: 0.2527 - val_loss: 0.1300 - val_mae: 0.2745
Epoch 74/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1066 - mae: 0.2525 - val_loss: 0.1298 - val_mae: 0.2740
Epoch 75/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1064 - mae: 0.2522 - val_loss: 0.1295 - val_mae: 0.2737
Epoch 76/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1062 - mae: 0.2521 - val_loss: 0.1301 - val_mae: 0.2745
Epoch 77/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1061 - mae: 0.2517 - val_loss: 0.1296 - val_mae: 0.2739
Epoch 78/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1059 - mae: 0.2516 - val_loss: 0.1295 - val_mae: 0.2735
Epoch 79/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1055 - mae: 0.2511 - val_loss: 0.1296 - val_mae: 0.2739
Epoch 80/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1054 - mae: 0.2508 - val_loss: 0.1296 - val_mae: 0.2739
Epoch 81/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1053 - mae: 0.2508 - val_loss: 0.1298 - val_mae: 0.2740
Epoch 82/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1051 - mae: 0.2505 - val_loss: 0.1296 - val_mae: 0.2736
Epoch 83/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1049 - mae: 0.2501 - val_loss: 0.1297 - val_mae: 0.2737
Epoch 84/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1047 - mae: 0.2499 - val_loss: 0.1296 - val_mae: 0.2735
Epoch 85/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1045 - mae: 0.2496 - val_loss: 0.1298 - val_mae: 0.2741

In [74]:
# Predict prices in log-transformed units
y_pred_log_v3 = model_v3.predict(X_test_v3).flatten()

# Convert predictions back to rupees
y_pred_v3 = np.expm1(y_pred_log_v3)

# Prevent negative predicted prices
y_pred_v3 = np.maximum(y_pred_v3, 0)

print("First 10 actual prices:")
print(y_test_v3.iloc[:10].values)

print("\nFirst 10 predicted prices:")
print(np.round(y_pred_v3[:10], 2))

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
First 10 actual prices:
[ 270000.  525000.  990000. 3800000.  229999.  325000.  210000.  500000.
  790000.  360000.]

First 10 predicted prices:
[4.1846391e+05 4.0055125e+05 1.1207570e+06 2.5094385e+06 2.1909850e+05
 3.1497888e+05 1.5295380e+05 4.1339544e+05 9.2983769e+05 4.0659291e+05]

In [85]:
mae_v3 = mean_absolute_error(y_test_v3, y_pred_v3)
mse_v3 = mean_squared_error(y_test_v3, y_pred_v3)
rmse_v3 = np.sqrt(mse_v3)
r2_v3 = r2_score(y_test_v3, y_pred_v3)

print(f"MAE  : ₹{mae_v3:,.2f}")
print(f"MSE  : {mse_v3:,.2f}")
print(f"RMSE : ₹{rmse_v3:,.2f}")
print(f"R²   : {r2_v3:.4f}")

MAE  : ₹143,838.49
MSE  : 122,250,290,832.66
RMSE : ₹349,643.09
R²   : 0.6205