In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import mysql.connector

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

print("All libraries imported successfully!")

All libraries imported successfully!

In [17]:
%pip install mysql

Requirement already satisfied: mysql in .\.venv\Lib\site-packages (0.0.3)
Requirement already satisfied: mysqlclient in .\.venv\Lib\site-packages (from mysql) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:

import os
from dotenv import load_dotenv
import mysql.connector

# Load environment variables from .env
load_dotenv()

# Connect to MySQL without hardcoding credentials
connection = mysql.connector.connect(
    host=os.getenv("MYSQL_HOST"),
    user=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"),
    database=os.getenv("MYSQL_DATABASE")
)

print("MySQL connected successfully!")

MySQL connected successfully!

In [19]:
query = """
SELECT *
FROM cars;
"""

df = pd.read_sql(query, connection)

df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_16940\2741079312.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, connection)

,id,car_name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,1,Maruti 800 AC,2007,60000.0,70000,Petrol,Individual,Manual,First Owner
1,2,Maruti Wagon R LXI Minor,2007,135000.0,50000,Petrol,Individual,Manual,First Owner
2,3,Hyundai Verna 1.6 SX,2012,600000.0,100000,Diesel,Individual,Manual,First Owner
3,4,Datsun RediGO T Option,2017,250000.0,46000,Petrol,Individual,Manual,First Owner
4,5,Honda Amaze VX i-DTEC,2014,450000.0,141000,Diesel,Individual,Manual,Second Owner

In [20]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 3577
Columns: 9

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3577 entries, 0 to 3576
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             3577 non-null   int64
 1   car_name       3577 non-null   str
 2   year           3577 non-null   int64
 3   selling_price  3577 non-null   float64
 4   km_driven      3577 non-null   int64
 5   fuel           3577 non-null   str
 6   seller_type    3577 non-null   str
 7   transmission   3577 non-null   str
 8   owner          3577 non-null   str
dtypes: float64(1), int64(3), str(5)
memory usage: 251.6 KB

In [22]:
df.isnull().sum()

id               0
car_name         0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [23]:
df.describe()

                id         year  selling_price      km_driven
count  3577.000000  3577.000000   3.577000e+03    3577.000000
mean   2087.193458  2012.962538   4.739125e+05   69250.545709
std    1254.720507     4.251759   5.093018e+05   47579.940016
min       1.000000  1992.000000   2.000000e+04       1.000000
25%    1026.000000  2010.000000   2.000000e+05   36000.000000
50%    2012.000000  2013.000000   3.500000e+05   60000.000000
75%    3193.000000  2016.000000   6.000000e+05   90000.000000
max    4340.000000  2020.000000   8.900000e+06  806599.000000

In [24]:
X=df.drop("selling_price",axis=1)
y=df["selling_price"]

In [25]:
print("Input features:")
print(X.columns)

print("\nTarget:")
print(y.name)

Input features:
Index(['id', 'car_name', 'year', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='str')

Target:
selling_price

In [26]:
X = X.drop("id", axis=1)

In [27]:
numeric_features = [
    "year",
    "car_age",
    "km_driven"
]

categorical_features = [
    "fuel",
    "seller_type",
    "transmission",
    "owner"
]

In [28]:
X = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True
)

In [29]:
X.head()

,car_name,year,km_driven,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti 800 AC,2007,70000,False,False,False,True,True,False,True,False,False,False,False
1,Maruti Wagon R LXI Minor,2007,50000,False,False,False,True,True,False,True,False,False,False,False
2,Hyundai Verna 1.6 SX,2012,100000,True,False,False,False,True,False,True,False,False,False,False
3,Datsun RediGO T Option,2017,46000,False,False,False,True,True,False,True,False,False,False,False
4,Honda Amaze VX i-DTEC,2014,141000,True,False,False,False,True,False,True,False,True,False,False

In [30]:
print(X.shape)

(3577, 14)

In [31]:
X = X.drop("car_name", axis=1)

In [32]:
X = X.astype(float)

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
print(tf.__version__)

2.22.0-rc0

In [36]:
model = Sequential([
    Dense(599, activation="relu"),
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1)
])

d:\PROJECTS\ANN_Car_Price\.venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [37]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=['mse']
)

In [38]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [40]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=1000,
    batch_size=52,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - loss: 452654465024.0000 - mse: 452654465024.0000 - val_loss: 519563018240.0000 - val_mse: 519562985472.0000
Epoch 2/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 450958786560.0000 - mse: 450958786560.0000 - val_loss: 513498185728.0000 - val_mse: 513498185728.0000
Epoch 3/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 428003983360.0000 - mse: 428003950592.0000 - val_loss: 454190628864.0000 - val_mse: 454190628864.0000
Epoch 4/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 309943566336.0000 - mse: 309943566336.0000 - val_loss: 253043752960.0000 - val_mse: 253043752960.0000
Epoch 5/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 155702853632.0000 - mse: 155702837248.0000 - val_loss: 171962253312.0000 - val_mse: 171962253312.0000
Epoch 6/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 132067975168.0000 - mse: 132067975168.0000 - val_loss: 160802586624.0000 - val_mse: 160802586624.0000
Epoch 7/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 125360881664.0000 - mse: 125360881664.0000 - val_loss: 154628833280.0000 - val_mse: 154628833280.0000
Epoch 8/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 121966092288.0000 - mse: 121966100480.0000 - val_loss: 151019012096.0000 - val_mse: 151019012096.0000
Epoch 9/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 120080334848.0000 - mse: 120080334848.0000 - val_loss: 148730068992.0000 - val_mse: 148730068992.0000
Epoch 10/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 118939738112.0000 - mse: 118939738112.0000 - val_loss: 147157663744.0000 - val_mse: 147157663744.0000
Epoch 11/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 118168379392.0000 - mse: 118168379392.0000 - val_loss: 145980719104.0000 - val_mse: 145980719104.0000
Epoch 12/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 117584879616.0000 - mse: 117584879616.0000 - val_loss: 145027317760.0000 - val_mse: 145027317760.0000
Epoch 13/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 117096464384.0000 - mse: 117096464384.0000 - val_loss: 144208084992.0000 - val_mse: 144208084992.0000
Epoch 14/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 116662140928.0000 - mse: 116662140928.0000 - val_loss: 143473590272.0000 - val_mse: 143473590272.0000
Epoch 15/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 116258258944.0000 - mse: 116258267136.0000 - val_loss: 142794883072.0000 - val_mse: 142794883072.0000
Epoch 16/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 115876102144.0000 - mse: 115876102144.0000 - val_loss: 142155104256.0000 - val_mse: 142155104256.0000
Epoch 17/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 115508371456.0000 - mse: 115508371456.0000 - val_loss: 141555843072.0000 - val_mse: 141555843072.0000
Epoch 18/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 115158851584.0000 - mse: 115158851584.0000 - val_loss: 140983959552.0000 - val_mse: 140983959552.0000
Epoch 19/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 114823684096.0000 - mse: 114823684096.0000 - val_loss: 140445564928.0000 - val_mse: 140445564928.0000
Epoch 20/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 114500681728.0000 - mse: 114500681728.0000 - val_loss: 139934285824.0000 - val_mse: 139934285824.0000
Epoch 21/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 114188050432.0000 - mse: 114188050432.0000 - val_loss: 139450810368.0000 - val_mse: 139450810368.0000
Epoch 22/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 113890754560.0000 - mse: 113890754560.0000 - val_loss: 138994204672.0000 - val_mse: 138994204672.0000
Epoch 23/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 113606860800.0000 - mse: 113606860800.0000 - val_loss: 138559930368.0000 - val_mse: 138559930368.0000
Epoch 24/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 113333166080.0000 - mse: 113333166080.0000 - val_loss: 138147692544.0000 - val_mse: 138147692544.0000
Epoch 25/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 113070219264.0000 - mse: 113070211072.0000 - val_loss: 137752559616.0000 - val_mse: 137752559616.0000
Epoch 26/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 112818003968.0000 - mse: 112818003968.0000 - val_loss: 137372753920.0000 - val_mse: 137372753920.0000
Epoch 27/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 112577536000.0000 - mse: 112577536000.0000 - val_loss: 137010593792.0000 - val_mse: 137010593792.0000
Epoch 28/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 112347226112.0000 - mse: 112347234304.0000 - val_loss: 136660099072.0000 - val_mse: 136660099072.0000
Epoch 29/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 112131604480.0000 - mse: 112131604480.0000 - val_loss: 136319524864.0000 - val_mse: 136319524864.0000
Epoch 30/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 111928426496.0000 - mse: 111928426496.0000 - val_loss: 135988502528.0000 - val_mse: 135988502528.0000
Epoch 31/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 111733686272.0000 - mse: 111733686272.0000 - val_loss: 135671119872.0000 - val_mse: 135671119872.0000
Epoch 32/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 111549014016.0000 - mse: 111549014016.0000 - val_loss: 135364591616.0000 - val_mse: 135364591616.0000
Epoch 33/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 111375073280.0000 - mse: 111375073280.0000 - val_loss: 135066394624.0000 - val_mse: 135066394624.0000
Epoch 34/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 111206891520.0000 - mse: 111206891520.0000 - val_loss: 134778961920.0000 - val_mse: 134778961920.0000
Epoch 35/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 111042273280.0000 - mse: 111042273280.0000 - val_loss: 134502268928.0000 - val_mse: 134502268928.0000
Epoch 36/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 110886608896.0000 - mse: 110886608896.0000 - val_loss: 134236979200.0000 - val_mse: 134236979200.0000
Epoch 37/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 110736359424.0000 - mse: 110736359424.0000 - val_loss: 133983887360.0000 - val_mse: 133983870976.0000
Epoch 38/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 110595514368.0000 - mse: 110595514368.0000 - val_loss: 133739446272.0000 - val_mse: 133739446272.0000
Epoch 39/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 110460780544.0000 - mse: 110460780544.0000 - val_loss: 133503967232.0000 - val_mse: 133503975424.0000
Epoch 40/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110332526592.0000 - mse: 110332526592.0000 - val_loss: 133277204480.0000 - val_mse: 133277204480.0000
Epoch 41/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110209097728.0000 - mse: 110209097728.0000 - val_loss: 133060509696.0000 - val_mse: 133060509696.0000
Epoch 42/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110089682944.0000 - mse: 110089682944.0000 - val_loss: 132855128064.0000 - val_mse: 132855111680.0000
Epoch 43/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109975658496.0000 - mse: 109975658496.0000 - val_loss: 132657479680.0000 - val_mse: 132657479680.0000
Epoch 44/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109865230336.0000 - mse: 109865230336.0000 - val_loss: 132468359168.0000 - val_mse: 132468359168.0000
Epoch 45/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109757906944.0000 - mse: 109757906944.0000 - val_loss: 132286988288.0000 - val_mse: 132286988288.0000
Epoch 46/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109653688320.0000 - mse: 109653688320.0000 - val_loss: 132113883136.0000 - val_mse: 132113883136.0000
Epoch 47/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109551960064.0000 - mse: 109551960064.0000 - val_loss: 131950370816.0000 - val_mse: 131950370816.0000
Epoch 48/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109455425536.0000 - mse: 109455425536.0000 - val_loss: 131794690048.0000 - val_mse: 131794690048.0000
Epoch 49/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109363683328.0000 - mse: 109363683328.0000 - val_loss: 131644809216.0000 - val_mse: 131644809216.0000
Epoch 50/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109272350720.0000 - mse: 109272350720.0000 - val_loss: 131500744704.0000 - val_mse: 131500744704.0000
Epoch 51/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 109185179648.0000 - mse: 109185179648.0000 - val_loss: 131361382400.0000 - val_mse: 131361382400.0000
Epoch 52/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109100105728.0000 - mse: 109100122112.0000 - val_loss: 131228180480.0000 - val_mse: 131228180480.0000
Epoch 53/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 109018087424.0000 - mse: 109018087424.0000 - val_loss: 131099582464.0000 - val_mse: 131099582464.0000
Epoch 54/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108937846784.0000 - mse: 108937854976.0000 - val_loss: 130976006144.0000 - val_mse: 130976006144.0000
Epoch 55/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108860112896.0000 - mse: 108860112896.0000 - val_loss: 130860048384.0000 - val_mse: 130860072960.0000
Epoch 56/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108783017984.0000 - mse: 108783017984.0000 - val_loss: 130747654144.0000 - val_mse: 130747654144.0000
Epoch 57/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108707659776.0000 - mse: 108707659776.0000 - val_loss: 130641674240.0000 - val_mse: 130641674240.0000
Epoch 58/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 108636561408.0000 - mse: 108636561408.0000 - val_loss: 130540953600.0000 - val_mse: 130540953600.0000
Epoch 59/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108567912448.0000 - mse: 108567912448.0000 - val_loss: 130443730944.0000 - val_mse: 130443730944.0000
Epoch 60/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 108500107264.0000 - mse: 108500107264.0000 - val_loss: 130350743552.0000 - val_mse: 130350743552.0000
Epoch 61/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 108434677760.0000 - mse: 108434694144.0000 - val_loss: 130262958080.0000 - val_mse: 130262958080.0000
Epoch 62/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 108370853888.0000 - mse: 108370845696.0000 - val_loss: 130178326528.0000 - val_mse: 130178326528.0000
Epoch 63/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108309544960.0000 - mse: 108309544960.0000 - val_loss: 130098200576.0000 - val_mse: 130098200576.0000
Epoch 64/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108248096768.0000 - mse: 108248096768.0000 - val_loss: 130019000320.0000 - val_mse: 130019000320.0000
Epoch 65/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108189876224.0000 - mse: 108189876224.0000 - val_loss: 129946476544.0000 - val_mse: 129946476544.0000
Epoch 66/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 108132065280.0000 - mse: 108132057088.0000 - val_loss: 129875050496.0000 - val_mse: 129875050496.0000
Epoch 67/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108075008000.0000 - mse: 108075008000.0000 - val_loss: 129808039936.0000 - val_mse: 129808039936.0000
Epoch 68/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 108020211712.0000 - mse: 108020211712.0000 - val_loss: 129745240064.0000 - val_mse: 129745240064.0000
Epoch 69/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107965685760.0000 - mse: 107965685760.0000 - val_loss: 129683324928.0000 - val_mse: 129683324928.0000
Epoch 70/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107913854976.0000 - mse: 107913854976.0000 - val_loss: 129624530944.0000 - val_mse: 129624530944.0000
Epoch 71/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107861991424.0000 - mse: 107861991424.0000 - val_loss: 129568096256.0000 - val_mse: 129568096256.0000
Epoch 72/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107810775040.0000 - mse: 107810775040.0000 - val_loss: 129514766336.0000 - val_mse: 129514766336.0000
Epoch 73/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107761352704.0000 - mse: 107761352704.0000 - val_loss: 129464475648.0000 - val_mse: 129464475648.0000
Epoch 74/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107712315392.0000 - mse: 107712315392.0000 - val_loss: 129414119424.0000 - val_mse: 129414119424.0000
Epoch 75/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107662778368.0000 - mse: 107662778368.0000 - val_loss: 129365368832.0000 - val_mse: 129365368832.0000
Epoch 76/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107613003776.0000 - mse: 107612995584.0000 - val_loss: 129320976384.0000 - val_mse: 129320976384.0000
Epoch 77/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107565047808.0000 - mse: 107565047808.0000 - val_loss: 129282048000.0000 - val_mse: 129282048000.0000
Epoch 78/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107517607936.0000 - mse: 107517607936.0000 - val_loss: 129243037696.0000 - val_mse: 129243037696.0000
Epoch 79/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107469496320.0000 - mse: 107469496320.0000 - val_loss: 129205993472.0000 - val_mse: 129205993472.0000
Epoch 80/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107422769152.0000 - mse: 107422769152.0000 - val_loss: 129173610496.0000 - val_mse: 129173610496.0000
Epoch 81/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107376656384.0000 - mse: 107376656384.0000 - val_loss: 129140039680.0000 - val_mse: 129140039680.0000
Epoch 82/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107331887104.0000 - mse: 107331887104.0000 - val_loss: 129112358912.0000 - val_mse: 129112358912.0000
Epoch 83/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107286634496.0000 - mse: 107286634496.0000 - val_loss: 129079787520.0000 - val_mse: 129079787520.0000
Epoch 84/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 107242127360.0000 - mse: 107242127360.0000 - val_loss: 129053270016.0000 - val_mse: 129053270016.0000
Epoch 85/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 107197980672.0000 - mse: 107197980672.0000 - val_loss: 129026793472.0000 - val_mse: 129026793472.0000
Epoch 86/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 107155480576.0000 - mse: 107155480576.0000 - val_loss: 129003192320.0000 - val_mse: 129003192320.0000
Epoch 87/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107112996864.0000 - mse: 107112988672.0000 - val_loss: 128979107840.0000 - val_mse: 128979107840.0000
Epoch 88/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 107071635456.0000 - mse: 107071635456.0000 - val_loss: 128963534848.0000 - val_mse: 128963534848.0000
Epoch 89/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 107026161664.0000 - mse: 107026161664.0000 - val_loss: 128939417600.0000 - val_mse: 128939417600.0000
Epoch 90/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106983940096.0000 - mse: 106983940096.0000 - val_loss: 128917561344.0000 - val_mse: 128917561344.0000
Epoch 91/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106943438848.0000 - mse: 106943438848.0000 - val_loss: 128897523712.0000 - val_mse: 128897523712.0000
Epoch 92/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106903191552.0000 - mse: 106903191552.0000 - val_loss: 128877682688.0000 - val_mse: 128877682688.0000
Epoch 93/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106863828992.0000 - mse: 106863828992.0000 - val_loss: 128858316800.0000 - val_mse: 128858316800.0000
Epoch 94/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106824769536.0000 - mse: 106824777728.0000 - val_loss: 128840515584.0000 - val_mse: 128840515584.0000
Epoch 95/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106786570240.0000 - mse: 106786578432.0000 - val_loss: 128830824448.0000 - val_mse: 128830824448.0000
Epoch 96/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106744135680.0000 - mse: 106744135680.0000 - val_loss: 128814047232.0000 - val_mse: 128814047232.0000
Epoch 97/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106707025920.0000 - mse: 106707025920.0000 - val_loss: 128797073408.0000 - val_mse: 128797073408.0000
Epoch 98/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106670645248.0000 - mse: 106670645248.0000 - val_loss: 128781459456.0000 - val_mse: 128781459456.0000
Epoch 99/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106634764288.0000 - mse: 106634764288.0000 - val_loss: 128767295488.0000 - val_mse: 128767295488.0000
Epoch 100/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106598285312.0000 - mse: 106598285312.0000 - val_loss: 128753451008.0000 - val_mse: 128753451008.0000
Epoch 101/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106564026368.0000 - mse: 106564026368.0000 - val_loss: 128740261888.0000 - val_mse: 128740261888.0000
Epoch 102/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106529046528.0000 - mse: 106529046528.0000 - val_loss: 128726573056.0000 - val_mse: 128726573056.0000
Epoch 103/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106495172608.0000 - mse: 106495172608.0000 - val_loss: 128714858496.0000 - val_mse: 128714858496.0000
Epoch 104/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106461470720.0000 - mse: 106461470720.0000 - val_loss: 128700645376.0000 - val_mse: 128700645376.0000
Epoch 105/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106427736064.0000 - mse: 106427736064.0000 - val_loss: 128689594368.0000 - val_mse: 128689594368.0000
Epoch 106/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106395344896.0000 - mse: 106395344896.0000 - val_loss: 128679698432.0000 - val_mse: 128679698432.0000
Epoch 107/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106363019264.0000 - mse: 106363019264.0000 - val_loss: 128667222016.0000 - val_mse: 128667222016.0000
Epoch 108/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106331316224.0000 - mse: 106331316224.0000 - val_loss: 128657006592.0000 - val_mse: 128657006592.0000
Epoch 109/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106299514880.0000 - mse: 106299514880.0000 - val_loss: 128648749056.0000 - val_mse: 128648749056.0000
Epoch 110/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106267811840.0000 - mse: 106267811840.0000 - val_loss: 128639270912.0000 - val_mse: 128639270912.0000
Epoch 111/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106237042688.0000 - mse: 106237042688.0000 - val_loss: 128631103488.0000 - val_mse: 128631103488.0000
Epoch 112/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106206806016.0000 - mse: 106206806016.0000 - val_loss: 128620781568.0000 - val_mse: 128620781568.0000
Epoch 113/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106176225280.0000 - mse: 106176225280.0000 - val_loss: 128612556800.0000 - val_mse: 128612556800.0000
Epoch 114/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106146193408.0000 - mse: 106146193408.0000 - val_loss: 128603947008.0000 - val_mse: 128603947008.0000
Epoch 115/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106114998272.0000 - mse: 106114998272.0000 - val_loss: 128596025344.0000 - val_mse: 128596025344.0000
Epoch 116/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106084859904.0000 - mse: 106084859904.0000 - val_loss: 128588865536.0000 - val_mse: 128588865536.0000
Epoch 117/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 106055720960.0000 - mse: 106055720960.0000 - val_loss: 128583426048.0000 - val_mse: 128583426048.0000
Epoch 118/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 106027024384.0000 - mse: 106027024384.0000 - val_loss: 128576118784.0000 - val_mse: 128576118784.0000
Epoch 119/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 105998614528.0000 - mse: 105998614528.0000 - val_loss: 128571744256.0000 - val_mse: 128571744256.0000
Epoch 120/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 105971154944.0000 - mse: 105971154944.0000 - val_loss: 128565501952.0000 - val_mse: 128565501952.0000
Epoch 121/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 105943121920.0000 - mse: 105943121920.0000 - val_loss: 128559620096.0000 - val_mse: 128559620096.0000
Epoch 122/1000
44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 105915580416.0000 - mse: 105915580416.0000 - val_loss: 128552108032.0000 - val_mse: 128552108032.0000
Epoch 123/1000

In [41]:
y_pred = model.predict(X_test)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [42]:
y_pred = y_pred.flatten()

In [43]:
print(y_pred[:10])

[5.0610812e+05 5.2198544e+05 6.7830838e+05 2.2314692e+06 1.5023888e+05
 2.6375006e+05 1.3899544e+05 7.1380119e+05 9.7797512e+05 3.2183906e+05]

In [44]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_pred)

print("MAE:", mae)

MAE: 184438.13839363653

In [45]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("MSE:", mse)

MSE: 163608256424.06677

In [46]:
from sklearn.metrics import r2_score

r2=r2_score(y_test , y_pred)
r2

0.49211016450348355

In [47]:
rmse = np.sqrt(mse)

print("RMSE:", rmse)

RMSE: 404485.17454174603

In [48]:
print("Model Evaluation")
print("---------------------------")
print("MAE  :", mae)
print("MSE  :", mse)
print("RMSE :", rmse)
print("R²   :", r2)

Model Evaluation
---------------------------
MAE  : 184438.13839363653
MSE  : 163608256424.06677
RMSE : 404485.17454174603
R²   : 0.49211016450348355

In [49]:
results = pd.DataFrame({
    "Actual Price": y_test.values,
    "Predicted Price": y_pred
})

results.head(20)

    Actual Price  Predicted Price
0       270000.0     5.061081e+05
1       525000.0     5.219854e+05
2       990000.0     6.783084e+05
3      3800000.0     2.231469e+06
4       229999.0     1.502389e+05
5       325000.0     2.637501e+05
6       210000.0     1.389954e+05
7       500000.0     7.138012e+05
8       790000.0     9.779751e+05
9       360000.0     3.218391e+05
10      250000.0     3.760309e+05
11      160000.0     2.418938e+05
12      500000.0     8.724080e+05
13      229999.0     2.464822e+05
14      360000.0     4.034436e+05
15      612000.0     3.889358e+05
16      350000.0     3.483168e+05
17      800000.0     1.005892e+06
18      160000.0     3.341737e+05
19      330000.0     3.130329e+05

In [50]:
results["Error"] = (
    results["Actual Price"] - results["Predicted Price"]
)

results.head(20)

    Actual Price  Predicted Price         Error
0       270000.0     5.061081e+05 -2.361081e+05
1       525000.0     5.219854e+05  3.014562e+03
2       990000.0     6.783084e+05  3.116916e+05
3      3800000.0     2.231469e+06  1.568531e+06
4       229999.0     1.502389e+05  7.976012e+04
5       325000.0     2.637501e+05  6.124994e+04
6       210000.0     1.389954e+05  7.100456e+04
7       500000.0     7.138012e+05 -2.138012e+05
8       790000.0     9.779751e+05 -1.879751e+05
9       360000.0     3.218391e+05  3.816094e+04
10      250000.0     3.760309e+05 -1.260309e+05
11      160000.0     2.418938e+05 -8.189380e+04
12      500000.0     8.724080e+05 -3.724080e+05
13      229999.0     2.464822e+05 -1.648319e+04
14      360000.0     4.034436e+05 -4.344362e+04
15      612000.0     3.889358e+05  2.230642e+05
16      350000.0     3.483168e+05  1.683219e+03
17      800000.0     1.005892e+06 -2.058924e+05
18      160000.0     3.341737e+05 -1.741737e+05
19      330000.0     3.130329e+05  1.696706e+04

In [51]:
query = """
SELECT
    id,
    car_name,
    year,
    km_driven,
    fuel,
    seller_type,
    transmission,
    owner,
    selling_price
FROM cars;
"""

df_v2 = pd.read_sql(query, connection)

print(df_v2.shape)
df_v2.head()

(3577, 9)

C:\Users\HP\AppData\Local\Temp\ipykernel_16940\1089843448.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_v2 = pd.read_sql(query, connection)

,id,car_name,year,km_driven,fuel,seller_type,transmission,owner,selling_price
0,1,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,60000.0
1,2,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,135000.0
2,3,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,600000.0
3,4,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,250000.0
4,5,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,450000.0

In [52]:
df_v2["car_brand"] = (
    df_v2["car_name"]
    .str.strip()
    .str.split()
    .str[0]
    .str.title()
)

print(df_v2[["car_name", "car_brand"]].head(15))

                           car_name  car_brand
0                     Maruti 800 AC     Maruti
1          Maruti Wagon R LXI Minor     Maruti
2              Hyundai Verna 1.6 SX    Hyundai
3            Datsun RediGO T Option     Datsun
4             Honda Amaze VX i-DTEC      Honda
5              Maruti Alto LX BSIII     Maruti
6         Hyundai Xcent 1.2 Kappa S    Hyundai
7          Tata Indigo Grand Petrol       Tata
8          Hyundai Creta 1.6 VTVT S    Hyundai
9          Maruti Celerio Green VXI     Maruti
10          Chevrolet Sail 1.2 Base  Chevrolet
11         Tata Indigo Grand Petrol       Tata
12  Toyota Corolla Altis 1.8 VL CVT     Toyota
13             Maruti Ciaz VXi Plus     Maruti
14      Hyundai Venue SX Opt Diesel    Hyundai

In [53]:
df_v2["car_age"]=2026-df["year"]

In [54]:
df_v2["car_age"]=2026-df["year"]
df_v2.head()

,id,car_name,year,km_driven,fuel,seller_type,transmission,owner,selling_price,car_brand,car_age
0,1,Maruti 800 AC,2007,70000,Petrol,Individual,Manual,First Owner,60000.0,Maruti,19
1,2,Maruti Wagon R LXI Minor,2007,50000,Petrol,Individual,Manual,First Owner,135000.0,Maruti,19
2,3,Hyundai Verna 1.6 SX,2012,100000,Diesel,Individual,Manual,First Owner,600000.0,Hyundai,14
3,4,Datsun RediGO T Option,2017,46000,Petrol,Individual,Manual,First Owner,250000.0,Datsun,9
4,5,Honda Amaze VX i-DTEC,2014,141000,Diesel,Individual,Manual,Second Owner,450000.0,Honda,12

In [55]:
numeric_features=[ "year",
                       "km_driven" ,
                       "car_age"
]

categorical_features=["car_name",
                           "fuel",
                           "seller_type",
                           "transmission",
                           "owner",
                           "car_brand"]

X_v2 = df_v2[numeric_features + categorical_features].copy()
y_v2 = df_v2["selling_price"].copy()

X_v2=pd.get_dummies(
    X_v2,
    columns=categorical_features,
    drop_first=True,
    dtype=int
)

print( X_v2.shape[1])
X_v2.head()

1532

,year,km_driven,car_age,car_name_Ambassador Classic 2000 Dsz,car_name_Ambassador Grand 1800 ISZ MPFI PW CL,car_name_Audi A4 1.8 TFSI,car_name_Audi A4 2.0 TDI,car_name_Audi A4 2.0 TDI 177 Bhp Premium Plus,car_name_Audi A4 3.0 TDI Quattro,car_name_Audi A4 30 TFSI Technology,...,car_brand_Mg,car_brand_Mitsubishi,car_brand_Nissan,car_brand_Opelcorsa,car_brand_Renault,car_brand_Skoda,car_brand_Tata,car_brand_Toyota,car_brand_Volkswagen,car_brand_Volvo
0,2007,70000,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2007,50000,19,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2012,100000,14,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2017,46000,9,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2014,141000,12,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [56]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train_v2,X_test_v2,y_train_v2,y_test_v2=train_test_split(
    X_v2,
    y_v2,
    test_size=0.20,
    random_state=42
)

scaler_v2 = StandardScaler()
X_train_v2=scaler_v2.fit_transform(X_train_v2)
X_test_v2 = scaler_v2.transform(X_test_v2)

In [57]:
model_v2=Sequential([
    Dense(128 , activation="relu",input_shape=(X_train_v2.shape[1],)),
    Dense(64 , activation="relu"),
    Dense(32 , activation="relu"),
    Dense(1)
])

model_v2.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

history_v2 = model_v2.fit(
    X_train_v2,
    y_train_v2,
    validation_split=0.2,
    epochs=100,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1

)

Epoch 1/100

d:\PROJECTS\ANN_Car_Price\.venv\Lib\site-packages\keras\src\layers\core\dense.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

72/72 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 452659478528.0000 - mae: 471160.1562 - val_loss: 519601913856.0000 - val_mae: 473829.9688
Epoch 2/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 451068493824.0000 - mae: 469625.5000 - val_loss: 516092821504.0000 - val_mae: 470342.7500
Epoch 3/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 435556548608.0000 - mae: 454732.2500 - val_loss: 494037237760.0000 - val_mae: 447706.3750
Epoch 4/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 377986023424.0000 - mae: 394879.5625 - val_loss: 436984250368.0000 - val_mae: 380312.8125
Epoch 5/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 279239163904.0000 - mae: 286651.3750 - val_loss: 378380910592.0000 - val_mae: 322152.4375
Epoch 6/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 209799610368.0000 - mae: 228657.8125 - val_loss: 359675297792.0000 - val_mae: 319398.4375
Epoch 7/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 183562043392.0000 - mae: 211390.5625 - val_loss: 350036164608.0000 - val_mae: 310845.8125
Epoch 8/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 166081314816.0000 - mae: 194185.7969 - val_loss: 341120483328.0000 - val_mae: 299518.0625
Epoch 9/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 150317744128.0000 - mae: 178247.7969 - val_loss: 332894044160.0000 - val_mae: 289097.7188
Epoch 10/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 135535484928.0000 - mae: 163729.1094 - val_loss: 325197856768.0000 - val_mae: 279527.0312
Epoch 11/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 121641541632.0000 - mae: 149998.3281 - val_loss: 318011015168.0000 - val_mae: 270923.5625
Epoch 12/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 108770508800.0000 - mae: 137076.0312 - val_loss: 311047749632.0000 - val_mae: 263080.5000
Epoch 13/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 97103912960.0000 - mae: 125216.7656 - val_loss: 303876603904.0000 - val_mae: 256329.2656
Epoch 14/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 86734749696.0000 - mae: 114476.5938 - val_loss: 296358379520.0000 - val_mae: 250592.6719
Epoch 15/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 77545766912.0000 - mae: 105539.3516 - val_loss: 288533151744.0000 - val_mae: 245866.0312
Epoch 16/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 69435236352.0000 - mae: 97917.2656 - val_loss: 280714772480.0000 - val_mae: 241786.2188
Epoch 17/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 62362210304.0000 - mae: 90967.0156 - val_loss: 273158291456.0000 - val_mae: 238261.0469
Epoch 18/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 56254500864.0000 - mae: 84897.7422 - val_loss: 266134962176.0000 - val_mae: 235145.2969
Epoch 19/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 50952695808.0000 - mae: 79844.2266 - val_loss: 259603972096.0000 - val_mae: 232108.1250
Epoch 20/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 46376652800.0000 - mae: 75635.8750 - val_loss: 253571432448.0000 - val_mae: 229351.9375
Epoch 21/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 42434568192.0000 - mae: 71909.5547 - val_loss: 248024350720.0000 - val_mae: 227114.4844
Epoch 22/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39022387200.0000 - mae: 68601.3047 - val_loss: 242980438016.0000 - val_mae: 225049.2188
Epoch 23/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 36021686272.0000 - mae: 65661.0312 - val_loss: 238400471040.0000 - val_mae: 223053.6562
Epoch 24/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33397563392.0000 - mae: 63005.7266 - val_loss: 234249977856.0000 - val_mae: 221162.1094
Epoch 25/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31076196352.0000 - mae: 60639.8047 - val_loss: 230434996224.0000 - val_mae: 219340.5156
Epoch 26/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 29021605888.0000 - mae: 58565.9180 - val_loss: 226903474176.0000 - val_mae: 217545.8750
Epoch 27/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 27194738688.0000 - mae: 56674.2188 - val_loss: 223675580416.0000 - val_mae: 215793.5938
Epoch 28/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 25566601216.0000 - mae: 54923.0508 - val_loss: 220759326720.0000 - val_mae: 214130.5625
Epoch 29/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24117002240.0000 - mae: 53400.4961 - val_loss: 217974849536.0000 - val_mae: 212453.0781
Epoch 30/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22822250496.0000 - mae: 52015.8320 - val_loss: 215483858944.0000 - val_mae: 210883.0781
Epoch 31/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 21664923648.0000 - mae: 50810.8672 - val_loss: 213081784320.0000 - val_mae: 209378.9062
Epoch 32/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20618397696.0000 - mae: 49674.0352 - val_loss: 210915885056.0000 - val_mae: 208111.3125
Epoch 33/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 19672616960.0000 - mae: 48669.5156 - val_loss: 208776773632.0000 - val_mae: 206896.0938
Epoch 34/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 18810875904.0000 - mae: 47743.4258 - val_loss: 206858076160.0000 - val_mae: 205836.7344
Epoch 35/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 18025263104.0000 - mae: 46934.4844 - val_loss: 204868173824.0000 - val_mae: 204804.5781
Epoch 36/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17303996416.0000 - mae: 46209.2930 - val_loss: 203067326464.0000 - val_mae: 203826.0312
Epoch 37/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16639621120.0000 - mae: 45598.8516 - val_loss: 201265479680.0000 - val_mae: 202834.8906
Epoch 38/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16020287488.0000 - mae: 45004.5078 - val_loss: 199522533376.0000 - val_mae: 201772.9219
Epoch 39/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 15444404224.0000 - mae: 44564.1016 - val_loss: 197855150080.0000 - val_mae: 200911.2031
Epoch 40/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 14901771264.0000 - mae: 44134.4492 - val_loss: 196164812800.0000 - val_mae: 199775.8906
Epoch 41/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14389099520.0000 - mae: 43754.3945 - val_loss: 194623619072.0000 - val_mae: 199030.3281
Epoch 42/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13900807168.0000 - mae: 43305.0742 - val_loss: 192932364288.0000 - val_mae: 197979.4062
Epoch 43/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13438414848.0000 - mae: 42970.1172 - val_loss: 191480397824.0000 - val_mae: 197171.4531
Epoch 44/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 13001042944.0000 - mae: 42610.6953 - val_loss: 189791911936.0000 - val_mae: 196095.9844
Epoch 45/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 12574572544.0000 - mae: 42324.4766 - val_loss: 188386017280.0000 - val_mae: 195440.8438
Epoch 46/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12168844288.0000 - mae: 41977.1914 - val_loss: 186701053952.0000 - val_mae: 194271.8125
Epoch 47/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11777759232.0000 - mae: 41775.4375 - val_loss: 185300090880.0000 - val_mae: 193822.6875
Epoch 48/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11402961920.0000 - mae: 41539.0664 - val_loss: 183634968576.0000 - val_mae: 192451.9688
Epoch 49/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11048200192.0000 - mae: 41438.5312 - val_loss: 182238724096.0000 - val_mae: 192179.6875
Epoch 50/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10696853504.0000 - mae: 41297.3516 - val_loss: 180663468032.0000 - val_mae: 190835.1562
Epoch 51/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10366127104.0000 - mae: 41151.0938 - val_loss: 179146653696.0000 - val_mae: 190295.2344
Epoch 52/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10029434880.0000 - mae: 40994.7422 - val_loss: 177709481984.0000 - val_mae: 189183.8125
Epoch 53/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9720510464.0000 - mae: 40860.8320 - val_loss: 176154836992.0000 - val_mae: 188459.9062
Epoch 54/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9408613376.0000 - mae: 40769.5117 - val_loss: 174693040128.0000 - val_mae: 187365.2500
Epoch 55/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 9127202816.0000 - mae: 40725.6211 - val_loss: 173208338432.0000 - val_mae: 186661.1875
Epoch 56/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 8838883328.0000 - mae: 40691.1211 - val_loss: 171682529280.0000 - val_mae: 185452.2500
Epoch 57/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 8571344384.0000 - mae: 40574.8125 - val_loss: 170217095168.0000 - val_mae: 184811.4375
Epoch 58/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 8298474496.0000 - mae: 40476.5195 - val_loss: 168678457344.0000 - val_mae: 183447.3125
Epoch 59/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 8045705216.0000 - mae: 40323.1641 - val_loss: 167245217792.0000 - val_mae: 182887.5469
Epoch 60/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7796751872.0000 - mae: 40306.1016 - val_loss: 165643583488.0000 - val_mae: 181434.0312
Epoch 61/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7562000896.0000 - mae: 40171.5156 - val_loss: 164272979968.0000 - val_mae: 181063.8750
Epoch 62/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7339729920.0000 - mae: 40185.7109 - val_loss: 162630631424.0000 - val_mae: 179357.7344
Epoch 63/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7120577024.0000 - mae: 40026.6055 - val_loss: 161325285376.0000 - val_mae: 179337.9062
Epoch 64/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 6915103744.0000 - mae: 40013.1289 - val_loss: 159656214528.0000 - val_mae: 177373.2188
Epoch 65/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6712733184.0000 - mae: 39862.9180 - val_loss: 158473863168.0000 - val_mae: 177510.3906
Epoch 66/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6526406144.0000 - mae: 39796.5859 - val_loss: 156864495616.0000 - val_mae: 175757.3281
Epoch 67/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6346112000.0000 - mae: 39687.4492 - val_loss: 155617574912.0000 - val_mae: 175704.4219
Epoch 68/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6181939200.0000 - mae: 39666.5430 - val_loss: 153999015936.0000 - val_mae: 173909.3906
Epoch 69/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6023366656.0000 - mae: 39582.0156 - val_loss: 152828297216.0000 - val_mae: 173947.3281
Epoch 70/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5877611520.0000 - mae: 39571.1133 - val_loss: 151322165248.0000 - val_mae: 172231.2969
Epoch 71/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5740322304.0000 - mae: 39534.9492 - val_loss: 150099427328.0000 - val_mae: 172123.3906
Epoch 72/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5605680640.0000 - mae: 39301.0820 - val_loss: 148745338880.0000 - val_mae: 170621.3906
Epoch 73/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5478452736.0000 - mae: 39135.5000 - val_loss: 147551059968.0000 - val_mae: 170452.5625
Epoch 74/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5365442048.0000 - mae: 38957.5820 - val_loss: 146192384000.0000 - val_mae: 168889.3750
Epoch 75/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5260028416.0000 - mae: 38869.2148 - val_loss: 145115693056.0000 - val_mae: 168827.5781
Epoch 76/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5163542528.0000 - mae: 38729.8945 - val_loss: 143929163776.0000 - val_mae: 167392.9375
Epoch 77/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 5073244160.0000 - mae: 38600.6328 - val_loss: 142888534016.0000 - val_mae: 167374.7500
Epoch 78/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4989836800.0000 - mae: 38498.7305 - val_loss: 141690355712.0000 - val_mae: 165896.0938
Epoch 79/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4911705600.0000 - mae: 38362.0469 - val_loss: 140876365824.0000 - val_mae: 166009.4531
Epoch 80/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4848337920.0000 - mae: 38260.9219 - val_loss: 139701075968.0000 - val_mae: 164518.4375
Epoch 81/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4784937984.0000 - mae: 38229.0312 - val_loss: 138804133888.0000 - val_mae: 164487.0312
Epoch 82/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4725728768.0000 - mae: 38078.1836 - val_loss: 137839411200.0000 - val_mae: 163200.1250
Epoch 83/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4676109312.0000 - mae: 37972.4688 - val_loss: 137048981504.0000 - val_mae: 163212.7031
Epoch 84/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4627789824.0000 - mae: 37800.8477 - val_loss: 136217640960.0000 - val_mae: 162073.2500
Epoch 85/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4583372800.0000 - mae: 37650.4844 - val_loss: 135434469376.0000 - val_mae: 162011.2188
Epoch 86/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4543478784.0000 - mae: 37497.2773 - val_loss: 134691094528.0000 - val_mae: 160985.8594
Epoch 87/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4511757312.0000 - mae: 37413.3398 - val_loss: 134109814784.0000 - val_mae: 161199.4219
Epoch 88/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 4476785664.0000 - mae: 37298.1016 - val_loss: 133326864384.0000 - val_mae: 160053.3750
Epoch 89/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4449276416.0000 - mae: 37151.3750 - val_loss: 132849254400.0000 - val_mae: 160325.8438
Epoch 90/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4421198336.0000 - mae: 37051.6953 - val_loss: 132059529216.0000 - val_mae: 159136.2031
Epoch 91/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4396406272.0000 - mae: 36968.5898 - val_loss: 131760701440.0000 - val_mae: 159614.3438
Epoch 92/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4373338624.0000 - mae: 36881.0742 - val_loss: 131026821120.0000 - val_mae: 158458.5469
Epoch 93/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4358713344.0000 - mae: 36841.5156 - val_loss: 130734219264.0000 - val_mae: 158919.2969
Epoch 94/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4337805312.0000 - mae: 36785.1016 - val_loss: 130120925184.0000 - val_mae: 157937.8906
Epoch 95/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4327019008.0000 - mae: 36788.5234 - val_loss: 129837031424.0000 - val_mae: 158337.9062
Epoch 96/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4306605056.0000 - mae: 36728.4219 - val_loss: 129334550528.0000 - val_mae: 157504.9844
Epoch 97/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4301207040.0000 - mae: 36677.4531 - val_loss: 128974553088.0000 - val_mae: 157832.4688
Epoch 98/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4280815104.0000 - mae: 36644.4297 - val_loss: 128709312512.0000 - val_mae: 157165.9688
Epoch 99/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4276635136.0000 - mae: 36566.2773 - val_loss: 128284884992.0000 - val_mae: 157461.4375
Epoch 100/100
72/72 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4252140288.0000 - mae: 36439.0352 - val_loss: 128019472384.0000 - val_mae: 156707.4844

In [58]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

y_pred_v2 = model_v2.predict(X_test_v2).flatten()

mae_v2 = mean_absolute_error(y_test_v2, y_pred_v2)
mse_v2 = mean_squared_error(y_test_v2, y_pred_v2)
rmse_v2 = np.sqrt(mse_v2)
r2_v2 = r2_score(y_test_v2, y_pred_v2)

print("ANN Version 2")
print("---------------------------")
print("MAE :", mae_v2)
print("MSE :", mse_v2)
print("RMSE:", rmse_v2)
print("R²  :", r2_v2)

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
ANN Version 2
---------------------------
MAE : 386263.6490135832
MSE : 486723264790.3468
RMSE: 697655.548813558
R²  : -0.5109371879494784

In [59]:


print("\nNumber of unique brands:")
print(df_v2["car_brand"].nunique())

Number of unique brands:
29

In [60]:
print("\nMost common brands:")
print(df_v2["car_brand"].value_counts().head(20))

Most common brands:
car_brand
Maruti           1072
Hyundai           637
Mahindra          328
Tata              308
Ford              220
Honda             216
Toyota            170
Chevrolet         151
Renault           110
Volkswagen         93
Nissan             52
Skoda              49
Fiat               32
Audi               31
Datsun             29
Bmw                25
Mercedes-Benz      21
Jaguar              5
Mitsubishi          5
Land                5
Name: count, dtype: int64

In [61]:
print(df_v2["selling_price"].describe())

print("\nMissing values:")
print(df_v2.isnull().sum())

print("\nDuplicate rows:")
print(df_v2.duplicated().sum())

count    3.577000e+03
mean     4.739125e+05
std      5.093018e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

Missing values:
id               0
car_name         0
year             0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
selling_price    0
car_brand        0
car_age          0
dtype: int64

Duplicate rows:
0

In [62]:
print("Training price statistics:")
print(y_train_v2.describe())

print("\nTesting price statistics:")
print(y_test_v2.describe())

Training price statistics:
count    2.861000e+03
mean     4.717467e+05
std      4.936159e+05
min      2.000000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      5.900000e+05
max      8.900000e+06
Name: selling_price, dtype: float64

Testing price statistics:
count    7.160000e+02
mean     4.825667e+05
std      5.679647e+05
min      3.500000e+04
25%      2.000000e+05
50%      3.500000e+05
75%      6.000000e+05
max      8.150000e+06
Name: selling_price, dtype: float64

In [63]:
import numpy as np
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Select input features
numeric_features = ["car_age", "km_driven"]
categorical_features = [
    "car_brand", "fuel", "seller_type", "transmission", "owner"
]

X_v3 = df_v2[numeric_features + categorical_features].copy()
y_v3 = df_v2["selling_price"].copy()

# Convert categorical columns into numeric columns
X_v3 = pd.get_dummies(
    X_v3,
    columns=categorical_features,
    drop_first=True,
    dtype=int
)

print("Input shape:", X_v3.shape)
print("Target shape:", y_v3.shape)
print("Missing values:", X_v3.isnull().sum().sum())

Input shape: (3577, 41)
Target shape: (3577,)
Missing values: 0

In [64]:
X_train_v3, X_test_v3, y_train_v3, y_test_v3 = train_test_split(
    X_v3, y_v3, test_size=0.20, random_state=42
)

# Scale input features
scaler_v3 = StandardScaler()

X_train_v3 = scaler_v3.fit_transform(X_train_v3)
X_test_v3 = scaler_v3.transform(X_test_v3)

# Transform target prices using logarithms
y_train_log_v3 = np.log1p(y_train_v3)
y_test_log_v3 = np.log1p(y_test_v3)

print("Training rows:", len(X_train_v3))
print("Testing rows:", len(X_test_v3))
print("Data preparation complete!")

Training rows: 2861
Testing rows: 716
Data preparation complete!

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping

# Set random seed for reproducibility
tf.keras.utils.set_random_seed(42)

# Build ANN model
model_v3 = Sequential([
    Input(shape=(X_train_v3.shape[1],)),
    Dense(1000, activation="relu"),
    Dense(500, activation="relu"),
    Dense(360, activation="relu"),
    Dense(128, activation="relu"),
    Dense(64, activation="relu"),
    Dense(32, activation="relu"),
    Dense(1)
])

# Compile the model
model_v3.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

# Stop training when validation loss stops improving
early_stop_v3 = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

model_v3.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 1000)           │        42,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 500)            │       500,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 360)            │       180,360 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_12 (Dense)                │ (None, 128)            │        46,208 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 779,437 (2.97 MB)

 Trainable params: 779,437 (2.97 MB)

 Non-trainable params: 0 (0.00 B)

In [66]:
history_v3 = model_v3.fit(
    X_train_v3,
    y_train_log_v3,
    validation_split=0.2,
    epochs=1000,
    batch_size=100,
    callbacks=[early_stop_v3],
    verbose=1
)

Epoch 1/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 3s 64ms/step - loss: 55.9852 - mae: 5.3655 - val_loss: 2.6904 - val_mae: 0.9968
Epoch 2/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 2.1707 - mae: 1.0867 - val_loss: 0.8234 - val_mae: 0.7138
Epoch 3/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.5886 - mae: 0.5799 - val_loss: 0.2800 - val_mae: 0.4187
Epoch 4/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.2808 - mae: 0.3993 - val_loss: 0.2194 - val_mae: 0.3606
Epoch 5/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1972 - mae: 0.3386 - val_loss: 0.1912 - val_mae: 0.3390
Epoch 6/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1669 - mae: 0.3133 - val_loss: 0.1759 - val_mae: 0.3232
Epoch 7/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1505 - mae: 0.2981 - val_loss: 0.1662 - val_mae: 0.3123
Epoch 8/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1413 - mae: 0.2893 - val_loss: 0.1608 - val_mae: 0.3077
Epoch 9/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1358 - mae: 0.2838 - val_loss: 0.1571 - val_mae: 0.3051
Epoch 10/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1319 - mae: 0.2798 - val_loss: 0.1546 - val_mae: 0.3035
Epoch 11/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1290 - mae: 0.2766 - val_loss: 0.1526 - val_mae: 0.3021
Epoch 12/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1267 - mae: 0.2740 - val_loss: 0.1511 - val_mae: 0.3012
Epoch 13/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1249 - mae: 0.2718 - val_loss: 0.1498 - val_mae: 0.3002
Epoch 14/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1233 - mae: 0.2700 - val_loss: 0.1486 - val_mae: 0.2990
Epoch 15/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1218 - mae: 0.2682 - val_loss: 0.1474 - val_mae: 0.2978
Epoch 16/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.1205 - mae: 0.2669 - val_loss: 0.1464 - val_mae: 0.2968
Epoch 17/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1194 - mae: 0.2656 - val_loss: 0.1453 - val_mae: 0.2955
Epoch 18/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1184 - mae: 0.2645 - val_loss: 0.1444 - val_mae: 0.2944
Epoch 19/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1175 - mae: 0.2635 - val_loss: 0.1436 - val_mae: 0.2935
Epoch 20/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1166 - mae: 0.2627 - val_loss: 0.1431 - val_mae: 0.2927
Epoch 21/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1159 - mae: 0.2620 - val_loss: 0.1428 - val_mae: 0.2923
Epoch 22/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1153 - mae: 0.2613 - val_loss: 0.1426 - val_mae: 0.2918
Epoch 23/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1148 - mae: 0.2608 - val_loss: 0.1425 - val_mae: 0.2916
Epoch 24/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1142 - mae: 0.2602 - val_loss: 0.1422 - val_mae: 0.2914
Epoch 25/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1138 - mae: 0.2598 - val_loss: 0.1423 - val_mae: 0.2913
Epoch 26/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1134 - mae: 0.2592 - val_loss: 0.1424 - val_mae: 0.2914
Epoch 27/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1131 - mae: 0.2589 - val_loss: 0.1426 - val_mae: 0.2914
Epoch 28/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1126 - mae: 0.2584 - val_loss: 0.1426 - val_mae: 0.2912
Epoch 29/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1126 - mae: 0.2584 - val_loss: 0.1428 - val_mae: 0.2911
Epoch 30/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1123 - mae: 0.2580 - val_loss: 0.1431 - val_mae: 0.2914
Epoch 31/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1122 - mae: 0.2578 - val_loss: 0.1433 - val_mae: 0.2915
Epoch 32/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1121 - mae: 0.2578 - val_loss: 0.1438 - val_mae: 0.2916
Epoch 33/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1122 - mae: 0.2578 - val_loss: 0.1444 - val_mae: 0.2921
Epoch 34/1000
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1124 - mae: 0.2583 - val_loss: 0.1455 - val_mae: 0.2929

In [67]:
# Predict prices in log-transformed units
y_pred_log_v3 = model_v3.predict(X_test_v3).flatten()

# Convert predictions back to rupees
y_pred_v3 = np.expm1(y_pred_log_v3)

# Prevent negative predicted prices
y_pred_v3 = np.maximum(y_pred_v3, 0)

print("First 10 actual prices:")
print(y_test_v3.iloc[:10].values)

print("\nFirst 10 predicted prices:")
print(np.round(y_pred_v3[:10], 2))

23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
First 10 actual prices:
[ 270000.  525000.  990000. 3800000.  229999.  325000.  210000.  500000.
  790000.  360000.]

First 10 predicted prices:
[4.1344709e+05 3.6201138e+05 1.1472792e+06 3.0889002e+06 2.5030798e+05
 2.9940941e+05 1.4957797e+05 4.8239984e+05 7.7788694e+05 3.6680481e+05]

In [68]:
mae_v3 = mean_absolute_error(y_test_v3, y_pred_v3)
mse_v3 = mean_squared_error(y_test_v3, y_pred_v3)
rmse_v3 = np.sqrt(mse_v3)
r2_v3 = r2_score(y_test_v3, y_pred_v3)

print(f"MAE  : ₹{mae_v3:,.2f}")
print(f"MSE  : {mse_v3:,.2f}")
print(f"RMSE : ₹{rmse_v3:,.2f}")
print(f"R²   : {r2_v3:.4f}")

MAE  : ₹150,063.74
MSE  : 126,937,394,839.04
RMSE : ₹356,282.75
R²   : 0.6059

In [69]:
import sys
print(sys.executable)

d:\PROJECTS\ANN_Car_Price\.venv\Scripts\python.exe